config system_bd_altera_arria10_hps_181_xmqpmyi_cfg;
		design system_bd_altera_arria10_hps_181_xmqpmyi;
		instance system_bd_altera_arria10_hps_181_xmqpmyi.fpga_interfaces use system_bd_altera_arria10_interface_generator_140.system_bd_altera_arria10_interface_generator_140_3ckwcii;
		instance system_bd_altera_arria10_hps_181_xmqpmyi.hps_io use system_bd_altera_arria10_hps_io_181.system_bd_altera_arria10_hps_io_181_sktkmzq;
endconfig

