// mcu_subsystem_altera_mm_interconnect_181_uxeiifq.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1.2 277

`timescale 1 ps / 1 ps
module mcu_subsystem_altera_mm_interconnect_181_uxeiifq (
		input  wire [30:0]  bridge_0_m0_address,                           //                             bridge_0_m0.address
		output wire         bridge_0_m0_waitrequest,                       //                                        .waitrequest
		input  wire [4:0]   bridge_0_m0_burstcount,                        //                                        .burstcount
		input  wire [31:0]  bridge_0_m0_byteenable,                        //                                        .byteenable
		input  wire         bridge_0_m0_read,                              //                                        .read
		output wire [255:0] bridge_0_m0_readdata,                          //                                        .readdata
		output wire         bridge_0_m0_readdatavalid,                     //                                        .readdatavalid
		input  wire         bridge_0_m0_write,                             //                                        .write
		input  wire [255:0] bridge_0_m0_writedata,                         //                                        .writedata
		input  wire         bridge_0_m0_debugaccess,                       //                                        .debugaccess
		output wire [25:0]  ddr3_ctrl_amm_0_address,                       //                         ddr3_ctrl_amm_0.address
		output wire         ddr3_ctrl_amm_0_write,                         //                                        .write
		output wire         ddr3_ctrl_amm_0_read,                          //                                        .read
		input  wire [255:0] ddr3_ctrl_amm_0_readdata,                      //                                        .readdata
		output wire [255:0] ddr3_ctrl_amm_0_writedata,                     //                                        .writedata
		output wire [6:0]   ddr3_ctrl_amm_0_burstcount,                    //                                        .burstcount
		output wire [31:0]  ddr3_ctrl_amm_0_byteenable,                    //                                        .byteenable
		input  wire         ddr3_ctrl_amm_0_readdatavalid,                 //                                        .readdatavalid
		input  wire         ddr3_ctrl_amm_0_waitrequest,                   //                                        .waitrequest
		input  wire         bridge_0_m0_reset_reset_bridge_in_reset_reset, // bridge_0_m0_reset_reset_bridge_in_reset.reset
		input  wire         ddr3_emif_usr_clk_clk                          //                       ddr3_emif_usr_clk.clk
	);

	wire          bridge_0_m0_translator_avalon_universal_master_0_waitrequest;   // bridge_0_m0_agent:av_waitrequest -> bridge_0_m0_translator:uav_waitrequest
	wire  [255:0] bridge_0_m0_translator_avalon_universal_master_0_readdata;      // bridge_0_m0_agent:av_readdata -> bridge_0_m0_translator:uav_readdata
	wire          bridge_0_m0_translator_avalon_universal_master_0_debugaccess;   // bridge_0_m0_translator:uav_debugaccess -> bridge_0_m0_agent:av_debugaccess
	wire   [30:0] bridge_0_m0_translator_avalon_universal_master_0_address;       // bridge_0_m0_translator:uav_address -> bridge_0_m0_agent:av_address
	wire          bridge_0_m0_translator_avalon_universal_master_0_read;          // bridge_0_m0_translator:uav_read -> bridge_0_m0_agent:av_read
	wire   [31:0] bridge_0_m0_translator_avalon_universal_master_0_byteenable;    // bridge_0_m0_translator:uav_byteenable -> bridge_0_m0_agent:av_byteenable
	wire          bridge_0_m0_translator_avalon_universal_master_0_readdatavalid; // bridge_0_m0_agent:av_readdatavalid -> bridge_0_m0_translator:uav_readdatavalid
	wire          bridge_0_m0_translator_avalon_universal_master_0_lock;          // bridge_0_m0_translator:uav_lock -> bridge_0_m0_agent:av_lock
	wire          bridge_0_m0_translator_avalon_universal_master_0_write;         // bridge_0_m0_translator:uav_write -> bridge_0_m0_agent:av_write
	wire  [255:0] bridge_0_m0_translator_avalon_universal_master_0_writedata;     // bridge_0_m0_translator:uav_writedata -> bridge_0_m0_agent:av_writedata
	wire    [9:0] bridge_0_m0_translator_avalon_universal_master_0_burstcount;    // bridge_0_m0_translator:uav_burstcount -> bridge_0_m0_agent:av_burstcount
	wire          rsp_mux_src_valid;                                              // rsp_mux:src_valid -> bridge_0_m0_agent:rp_valid
	wire  [370:0] rsp_mux_src_data;                                               // rsp_mux:src_data -> bridge_0_m0_agent:rp_data
	wire          rsp_mux_src_ready;                                              // bridge_0_m0_agent:rp_ready -> rsp_mux:src_ready
	wire    [0:0] rsp_mux_src_channel;                                            // rsp_mux:src_channel -> bridge_0_m0_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                      // rsp_mux:src_startofpacket -> bridge_0_m0_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                        // rsp_mux:src_endofpacket -> bridge_0_m0_agent:rp_endofpacket
	wire  [255:0] ddr3_ctrl_amm_0_agent_m0_readdata;                              // ddr3_ctrl_amm_0_translator:uav_readdata -> ddr3_ctrl_amm_0_agent:m0_readdata
	wire          ddr3_ctrl_amm_0_agent_m0_waitrequest;                           // ddr3_ctrl_amm_0_translator:uav_waitrequest -> ddr3_ctrl_amm_0_agent:m0_waitrequest
	wire          ddr3_ctrl_amm_0_agent_m0_debugaccess;                           // ddr3_ctrl_amm_0_agent:m0_debugaccess -> ddr3_ctrl_amm_0_translator:uav_debugaccess
	wire   [30:0] ddr3_ctrl_amm_0_agent_m0_address;                               // ddr3_ctrl_amm_0_agent:m0_address -> ddr3_ctrl_amm_0_translator:uav_address
	wire   [31:0] ddr3_ctrl_amm_0_agent_m0_byteenable;                            // ddr3_ctrl_amm_0_agent:m0_byteenable -> ddr3_ctrl_amm_0_translator:uav_byteenable
	wire          ddr3_ctrl_amm_0_agent_m0_read;                                  // ddr3_ctrl_amm_0_agent:m0_read -> ddr3_ctrl_amm_0_translator:uav_read
	wire          ddr3_ctrl_amm_0_agent_m0_readdatavalid;                         // ddr3_ctrl_amm_0_translator:uav_readdatavalid -> ddr3_ctrl_amm_0_agent:m0_readdatavalid
	wire          ddr3_ctrl_amm_0_agent_m0_lock;                                  // ddr3_ctrl_amm_0_agent:m0_lock -> ddr3_ctrl_amm_0_translator:uav_lock
	wire  [255:0] ddr3_ctrl_amm_0_agent_m0_writedata;                             // ddr3_ctrl_amm_0_agent:m0_writedata -> ddr3_ctrl_amm_0_translator:uav_writedata
	wire          ddr3_ctrl_amm_0_agent_m0_write;                                 // ddr3_ctrl_amm_0_agent:m0_write -> ddr3_ctrl_amm_0_translator:uav_write
	wire   [11:0] ddr3_ctrl_amm_0_agent_m0_burstcount;                            // ddr3_ctrl_amm_0_agent:m0_burstcount -> ddr3_ctrl_amm_0_translator:uav_burstcount
	wire          ddr3_ctrl_amm_0_agent_rf_source_valid;                          // ddr3_ctrl_amm_0_agent:rf_source_valid -> ddr3_ctrl_amm_0_agent_rsp_fifo:in_valid
	wire  [371:0] ddr3_ctrl_amm_0_agent_rf_source_data;                           // ddr3_ctrl_amm_0_agent:rf_source_data -> ddr3_ctrl_amm_0_agent_rsp_fifo:in_data
	wire          ddr3_ctrl_amm_0_agent_rf_source_ready;                          // ddr3_ctrl_amm_0_agent_rsp_fifo:in_ready -> ddr3_ctrl_amm_0_agent:rf_source_ready
	wire          ddr3_ctrl_amm_0_agent_rf_source_startofpacket;                  // ddr3_ctrl_amm_0_agent:rf_source_startofpacket -> ddr3_ctrl_amm_0_agent_rsp_fifo:in_startofpacket
	wire          ddr3_ctrl_amm_0_agent_rf_source_endofpacket;                    // ddr3_ctrl_amm_0_agent:rf_source_endofpacket -> ddr3_ctrl_amm_0_agent_rsp_fifo:in_endofpacket
	wire          ddr3_ctrl_amm_0_agent_rsp_fifo_out_valid;                       // ddr3_ctrl_amm_0_agent_rsp_fifo:out_valid -> ddr3_ctrl_amm_0_agent:rf_sink_valid
	wire  [371:0] ddr3_ctrl_amm_0_agent_rsp_fifo_out_data;                        // ddr3_ctrl_amm_0_agent_rsp_fifo:out_data -> ddr3_ctrl_amm_0_agent:rf_sink_data
	wire          ddr3_ctrl_amm_0_agent_rsp_fifo_out_ready;                       // ddr3_ctrl_amm_0_agent:rf_sink_ready -> ddr3_ctrl_amm_0_agent_rsp_fifo:out_ready
	wire          ddr3_ctrl_amm_0_agent_rsp_fifo_out_startofpacket;               // ddr3_ctrl_amm_0_agent_rsp_fifo:out_startofpacket -> ddr3_ctrl_amm_0_agent:rf_sink_startofpacket
	wire          ddr3_ctrl_amm_0_agent_rsp_fifo_out_endofpacket;                 // ddr3_ctrl_amm_0_agent_rsp_fifo:out_endofpacket -> ddr3_ctrl_amm_0_agent:rf_sink_endofpacket
	wire          ddr3_ctrl_amm_0_agent_rdata_fifo_src_valid;                     // ddr3_ctrl_amm_0_agent:rdata_fifo_src_valid -> ddr3_ctrl_amm_0_agent:rdata_fifo_sink_valid
	wire  [257:0] ddr3_ctrl_amm_0_agent_rdata_fifo_src_data;                      // ddr3_ctrl_amm_0_agent:rdata_fifo_src_data -> ddr3_ctrl_amm_0_agent:rdata_fifo_sink_data
	wire          ddr3_ctrl_amm_0_agent_rdata_fifo_src_ready;                     // ddr3_ctrl_amm_0_agent:rdata_fifo_sink_ready -> ddr3_ctrl_amm_0_agent:rdata_fifo_src_ready
	wire          cmd_mux_src_valid;                                              // cmd_mux:src_valid -> ddr3_ctrl_amm_0_agent:cp_valid
	wire  [370:0] cmd_mux_src_data;                                               // cmd_mux:src_data -> ddr3_ctrl_amm_0_agent:cp_data
	wire          cmd_mux_src_ready;                                              // ddr3_ctrl_amm_0_agent:cp_ready -> cmd_mux:src_ready
	wire    [0:0] cmd_mux_src_channel;                                            // cmd_mux:src_channel -> ddr3_ctrl_amm_0_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                      // cmd_mux:src_startofpacket -> ddr3_ctrl_amm_0_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                        // cmd_mux:src_endofpacket -> ddr3_ctrl_amm_0_agent:cp_endofpacket
	wire          bridge_0_m0_agent_cp_valid;                                     // bridge_0_m0_agent:cp_valid -> router:sink_valid
	wire  [370:0] bridge_0_m0_agent_cp_data;                                      // bridge_0_m0_agent:cp_data -> router:sink_data
	wire          bridge_0_m0_agent_cp_ready;                                     // router:sink_ready -> bridge_0_m0_agent:cp_ready
	wire          bridge_0_m0_agent_cp_startofpacket;                             // bridge_0_m0_agent:cp_startofpacket -> router:sink_startofpacket
	wire          bridge_0_m0_agent_cp_endofpacket;                               // bridge_0_m0_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                               // router:src_valid -> cmd_demux:sink_valid
	wire  [370:0] router_src_data;                                                // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                               // cmd_demux:sink_ready -> router:src_ready
	wire    [0:0] router_src_channel;                                             // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                       // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                         // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          ddr3_ctrl_amm_0_agent_rp_valid;                                 // ddr3_ctrl_amm_0_agent:rp_valid -> router_001:sink_valid
	wire  [370:0] ddr3_ctrl_amm_0_agent_rp_data;                                  // ddr3_ctrl_amm_0_agent:rp_data -> router_001:sink_data
	wire          ddr3_ctrl_amm_0_agent_rp_ready;                                 // router_001:sink_ready -> ddr3_ctrl_amm_0_agent:rp_ready
	wire          ddr3_ctrl_amm_0_agent_rp_startofpacket;                         // ddr3_ctrl_amm_0_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          ddr3_ctrl_amm_0_agent_rp_endofpacket;                           // ddr3_ctrl_amm_0_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                           // router_001:src_valid -> rsp_demux:sink_valid
	wire  [370:0] router_001_src_data;                                            // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                           // rsp_demux:sink_ready -> router_001:src_ready
	wire    [0:0] router_001_src_channel;                                         // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                   // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                     // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          cmd_demux_src0_valid;                                           // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [370:0] cmd_demux_src0_data;                                            // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                           // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [0:0] cmd_demux_src0_channel;                                         // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                   // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                     // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                           // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [370:0] rsp_demux_src0_data;                                            // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                           // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [0:0] rsp_demux_src0_channel;                                         // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                   // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                     // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket

	mcu_subsystem_altera_merlin_master_translator_181_mhudjri #(
		.AV_ADDRESS_W                (31),
		.AV_DATA_W                   (256),
		.AV_BURSTCOUNT_W             (5),
		.AV_BYTEENABLE_W             (32),
		.UAV_ADDRESS_W               (31),
		.UAV_BURSTCOUNT_W            (10),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (32),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0),
		.SYNC_RESET                  (0),
		.WAITREQUEST_ALLOWANCE       (0)
	) bridge_0_m0_translator (
		.clk                    (ddr3_emif_usr_clk_clk),                                          //   input,    width = 1,                       clk.clk
		.reset                  (bridge_0_m0_reset_reset_bridge_in_reset_reset),                  //   input,    width = 1,                     reset.reset
		.uav_address            (bridge_0_m0_translator_avalon_universal_master_0_address),       //  output,   width = 31, avalon_universal_master_0.address
		.uav_burstcount         (bridge_0_m0_translator_avalon_universal_master_0_burstcount),    //  output,   width = 10,                          .burstcount
		.uav_read               (bridge_0_m0_translator_avalon_universal_master_0_read),          //  output,    width = 1,                          .read
		.uav_write              (bridge_0_m0_translator_avalon_universal_master_0_write),         //  output,    width = 1,                          .write
		.uav_waitrequest        (bridge_0_m0_translator_avalon_universal_master_0_waitrequest),   //   input,    width = 1,                          .waitrequest
		.uav_readdatavalid      (bridge_0_m0_translator_avalon_universal_master_0_readdatavalid), //   input,    width = 1,                          .readdatavalid
		.uav_byteenable         (bridge_0_m0_translator_avalon_universal_master_0_byteenable),    //  output,   width = 32,                          .byteenable
		.uav_readdata           (bridge_0_m0_translator_avalon_universal_master_0_readdata),      //   input,  width = 256,                          .readdata
		.uav_writedata          (bridge_0_m0_translator_avalon_universal_master_0_writedata),     //  output,  width = 256,                          .writedata
		.uav_lock               (bridge_0_m0_translator_avalon_universal_master_0_lock),          //  output,    width = 1,                          .lock
		.uav_debugaccess        (bridge_0_m0_translator_avalon_universal_master_0_debugaccess),   //  output,    width = 1,                          .debugaccess
		.av_address             (bridge_0_m0_address),                                            //   input,   width = 31,      avalon_anti_master_0.address
		.av_waitrequest         (bridge_0_m0_waitrequest),                                        //  output,    width = 1,                          .waitrequest
		.av_burstcount          (bridge_0_m0_burstcount),                                         //   input,    width = 5,                          .burstcount
		.av_byteenable          (bridge_0_m0_byteenable),                                         //   input,   width = 32,                          .byteenable
		.av_read                (bridge_0_m0_read),                                               //   input,    width = 1,                          .read
		.av_readdata            (bridge_0_m0_readdata),                                           //  output,  width = 256,                          .readdata
		.av_readdatavalid       (bridge_0_m0_readdatavalid),                                      //  output,    width = 1,                          .readdatavalid
		.av_write               (bridge_0_m0_write),                                              //   input,    width = 1,                          .write
		.av_writedata           (bridge_0_m0_writedata),                                          //   input,  width = 256,                          .writedata
		.av_debugaccess         (bridge_0_m0_debugaccess),                                        //   input,    width = 1,                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                           // (terminated),                                         
		.av_begintransfer       (1'b0),                                                           // (terminated),                                         
		.av_chipselect          (1'b0),                                                           // (terminated),                                         
		.av_lock                (1'b0),                                                           // (terminated),                                         
		.uav_clken              (),                                                               // (terminated),                                         
		.av_clken               (1'b1),                                                           // (terminated),                                         
		.uav_response           (2'b00),                                                          // (terminated),                                         
		.av_response            (),                                                               // (terminated),                                         
		.uav_writeresponsevalid (1'b0),                                                           // (terminated),                                         
		.av_writeresponsevalid  ()                                                                // (terminated),                                         
	);

	mcu_subsystem_altera_merlin_slave_translator_181_5aswt6a #(
		.AV_ADDRESS_W                   (26),
		.AV_DATA_W                      (256),
		.UAV_DATA_W                     (256),
		.AV_BURSTCOUNT_W                (7),
		.AV_BYTEENABLE_W                (32),
		.UAV_BYTEENABLE_W               (32),
		.UAV_ADDRESS_W                  (31),
		.UAV_BURSTCOUNT_W               (12),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (32),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0),
		.WAITREQUEST_ALLOWANCE          (0),
		.SYNC_RESET                     (0)
	) ddr3_ctrl_amm_0_translator (
		.clk                    (ddr3_emif_usr_clk_clk),                         //   input,    width = 1,                      clk.clk
		.reset                  (bridge_0_m0_reset_reset_bridge_in_reset_reset), //   input,    width = 1,                    reset.reset
		.uav_address            (ddr3_ctrl_amm_0_agent_m0_address),              //   input,   width = 31, avalon_universal_slave_0.address
		.uav_burstcount         (ddr3_ctrl_amm_0_agent_m0_burstcount),           //   input,   width = 12,                         .burstcount
		.uav_read               (ddr3_ctrl_amm_0_agent_m0_read),                 //   input,    width = 1,                         .read
		.uav_write              (ddr3_ctrl_amm_0_agent_m0_write),                //   input,    width = 1,                         .write
		.uav_waitrequest        (ddr3_ctrl_amm_0_agent_m0_waitrequest),          //  output,    width = 1,                         .waitrequest
		.uav_readdatavalid      (ddr3_ctrl_amm_0_agent_m0_readdatavalid),        //  output,    width = 1,                         .readdatavalid
		.uav_byteenable         (ddr3_ctrl_amm_0_agent_m0_byteenable),           //   input,   width = 32,                         .byteenable
		.uav_readdata           (ddr3_ctrl_amm_0_agent_m0_readdata),             //  output,  width = 256,                         .readdata
		.uav_writedata          (ddr3_ctrl_amm_0_agent_m0_writedata),            //   input,  width = 256,                         .writedata
		.uav_lock               (ddr3_ctrl_amm_0_agent_m0_lock),                 //   input,    width = 1,                         .lock
		.uav_debugaccess        (ddr3_ctrl_amm_0_agent_m0_debugaccess),          //   input,    width = 1,                         .debugaccess
		.av_address             (ddr3_ctrl_amm_0_address),                       //  output,   width = 26,      avalon_anti_slave_0.address
		.av_write               (ddr3_ctrl_amm_0_write),                         //  output,    width = 1,                         .write
		.av_read                (ddr3_ctrl_amm_0_read),                          //  output,    width = 1,                         .read
		.av_readdata            (ddr3_ctrl_amm_0_readdata),                      //   input,  width = 256,                         .readdata
		.av_writedata           (ddr3_ctrl_amm_0_writedata),                     //  output,  width = 256,                         .writedata
		.av_burstcount          (ddr3_ctrl_amm_0_burstcount),                    //  output,    width = 7,                         .burstcount
		.av_byteenable          (ddr3_ctrl_amm_0_byteenable),                    //  output,   width = 32,                         .byteenable
		.av_readdatavalid       (ddr3_ctrl_amm_0_readdatavalid),                 //   input,    width = 1,                         .readdatavalid
		.av_waitrequest         (ddr3_ctrl_amm_0_waitrequest),                   //   input,    width = 1,                         .waitrequest
		.av_begintransfer       (),                                              // (terminated),                                        
		.av_beginbursttransfer  (),                                              // (terminated),                                        
		.av_writebyteenable     (),                                              // (terminated),                                        
		.av_lock                (),                                              // (terminated),                                        
		.av_chipselect          (),                                              // (terminated),                                        
		.av_clken               (),                                              // (terminated),                                        
		.uav_clken              (1'b0),                                          // (terminated),                                        
		.av_debugaccess         (),                                              // (terminated),                                        
		.av_outputenable        (),                                              // (terminated),                                        
		.uav_response           (),                                              // (terminated),                                        
		.av_response            (2'b00),                                         // (terminated),                                        
		.uav_writeresponsevalid (),                                              // (terminated),                                        
		.av_writeresponsevalid  (1'b0)                                           // (terminated),                                        
	);

	mcu_subsystem_altera_merlin_master_agent_181_t5eyqrq #(
		.PKT_WUNIQUE               (370),
		.PKT_DOMAIN_H              (369),
		.PKT_DOMAIN_L              (368),
		.PKT_SNOOP_H               (367),
		.PKT_SNOOP_L               (364),
		.PKT_BARRIER_H             (363),
		.PKT_BARRIER_L             (362),
		.PKT_ORI_BURST_SIZE_H      (361),
		.PKT_ORI_BURST_SIZE_L      (359),
		.PKT_RESPONSE_STATUS_H     (358),
		.PKT_RESPONSE_STATUS_L     (357),
		.PKT_QOS_H                 (346),
		.PKT_QOS_L                 (346),
		.PKT_DATA_SIDEBAND_H       (344),
		.PKT_DATA_SIDEBAND_L       (344),
		.PKT_ADDR_SIDEBAND_H       (343),
		.PKT_ADDR_SIDEBAND_L       (343),
		.PKT_BURST_TYPE_H          (342),
		.PKT_BURST_TYPE_L          (341),
		.PKT_CACHE_H               (356),
		.PKT_CACHE_L               (353),
		.PKT_THREAD_ID_H           (349),
		.PKT_THREAD_ID_L           (349),
		.PKT_BURST_SIZE_H          (340),
		.PKT_BURST_SIZE_L          (338),
		.PKT_TRANS_EXCLUSIVE       (324),
		.PKT_TRANS_LOCK            (323),
		.PKT_BEGIN_BURST           (345),
		.PKT_PROTECTION_H          (352),
		.PKT_PROTECTION_L          (350),
		.PKT_BURSTWRAP_H           (337),
		.PKT_BURSTWRAP_L           (337),
		.PKT_BYTE_CNT_H            (336),
		.PKT_BYTE_CNT_L            (325),
		.PKT_ADDR_H                (318),
		.PKT_ADDR_L                (288),
		.PKT_TRANS_COMPRESSED_READ (319),
		.PKT_TRANS_POSTED          (320),
		.PKT_TRANS_WRITE           (321),
		.PKT_TRANS_READ            (322),
		.PKT_DATA_H                (255),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (287),
		.PKT_BYTEEN_L              (256),
		.PKT_SRC_ID_H              (347),
		.PKT_SRC_ID_L              (347),
		.PKT_DEST_ID_H             (348),
		.PKT_DEST_ID_L             (348),
		.ST_DATA_W                 (371),
		.ST_CHANNEL_W              (1),
		.AV_BURSTCOUNT_W           (10),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.DOMAIN_VALUE              (3),
		.BARRIER_VALUE             (0),
		.SNOOP_VALUE               (0),
		.WUNIQUE_VALUE             (0),
		.SYNC_RESET                (0)
	) bridge_0_m0_agent (
		.clk                   (ddr3_emif_usr_clk_clk),                                          //   input,    width = 1,       clk.clk
		.reset                 (bridge_0_m0_reset_reset_bridge_in_reset_reset),                  //   input,    width = 1, clk_reset.reset
		.av_address            (bridge_0_m0_translator_avalon_universal_master_0_address),       //   input,   width = 31,        av.address
		.av_write              (bridge_0_m0_translator_avalon_universal_master_0_write),         //   input,    width = 1,          .write
		.av_read               (bridge_0_m0_translator_avalon_universal_master_0_read),          //   input,    width = 1,          .read
		.av_writedata          (bridge_0_m0_translator_avalon_universal_master_0_writedata),     //   input,  width = 256,          .writedata
		.av_readdata           (bridge_0_m0_translator_avalon_universal_master_0_readdata),      //  output,  width = 256,          .readdata
		.av_waitrequest        (bridge_0_m0_translator_avalon_universal_master_0_waitrequest),   //  output,    width = 1,          .waitrequest
		.av_readdatavalid      (bridge_0_m0_translator_avalon_universal_master_0_readdatavalid), //  output,    width = 1,          .readdatavalid
		.av_byteenable         (bridge_0_m0_translator_avalon_universal_master_0_byteenable),    //   input,   width = 32,          .byteenable
		.av_burstcount         (bridge_0_m0_translator_avalon_universal_master_0_burstcount),    //   input,   width = 10,          .burstcount
		.av_debugaccess        (bridge_0_m0_translator_avalon_universal_master_0_debugaccess),   //   input,    width = 1,          .debugaccess
		.av_lock               (bridge_0_m0_translator_avalon_universal_master_0_lock),          //   input,    width = 1,          .lock
		.cp_valid              (bridge_0_m0_agent_cp_valid),                                     //  output,    width = 1,        cp.valid
		.cp_data               (bridge_0_m0_agent_cp_data),                                      //  output,  width = 371,          .data
		.cp_startofpacket      (bridge_0_m0_agent_cp_startofpacket),                             //  output,    width = 1,          .startofpacket
		.cp_endofpacket        (bridge_0_m0_agent_cp_endofpacket),                               //  output,    width = 1,          .endofpacket
		.cp_ready              (bridge_0_m0_agent_cp_ready),                                     //   input,    width = 1,          .ready
		.rp_valid              (rsp_mux_src_valid),                                              //   input,    width = 1,        rp.valid
		.rp_data               (rsp_mux_src_data),                                               //   input,  width = 371,          .data
		.rp_channel            (rsp_mux_src_channel),                                            //   input,    width = 1,          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                      //   input,    width = 1,          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                        //   input,    width = 1,          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                              //  output,    width = 1,          .ready
		.av_response           (),                                                               // (terminated),                         
		.av_writeresponsevalid ()                                                                // (terminated),                         
	);

	mcu_subsystem_altera_merlin_slave_agent_181_a7g37xa #(
		.PKT_ORI_BURST_SIZE_H      (361),
		.PKT_ORI_BURST_SIZE_L      (359),
		.PKT_RESPONSE_STATUS_H     (358),
		.PKT_RESPONSE_STATUS_L     (357),
		.PKT_BURST_SIZE_H          (340),
		.PKT_BURST_SIZE_L          (338),
		.PKT_TRANS_LOCK            (323),
		.PKT_BEGIN_BURST           (345),
		.PKT_PROTECTION_H          (352),
		.PKT_PROTECTION_L          (350),
		.PKT_BURSTWRAP_H           (337),
		.PKT_BURSTWRAP_L           (337),
		.PKT_BYTE_CNT_H            (336),
		.PKT_BYTE_CNT_L            (325),
		.PKT_ADDR_H                (318),
		.PKT_ADDR_L                (288),
		.PKT_TRANS_COMPRESSED_READ (319),
		.PKT_TRANS_POSTED          (320),
		.PKT_TRANS_WRITE           (321),
		.PKT_TRANS_READ            (322),
		.PKT_DATA_H                (255),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (287),
		.PKT_BYTEEN_L              (256),
		.PKT_SRC_ID_H              (347),
		.PKT_SRC_ID_L              (347),
		.PKT_DEST_ID_H             (348),
		.PKT_DEST_ID_L             (348),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (1),
		.ST_DATA_W                 (371),
		.AVS_BURSTCOUNT_W          (12),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0),
		.SYNC_RESET                (0)
	) ddr3_ctrl_amm_0_agent (
		.clk                     (ddr3_emif_usr_clk_clk),                            //   input,    width = 1,             clk.clk
		.reset                   (bridge_0_m0_reset_reset_bridge_in_reset_reset),    //   input,    width = 1,       clk_reset.reset
		.m0_address              (ddr3_ctrl_amm_0_agent_m0_address),                 //  output,   width = 31,              m0.address
		.m0_burstcount           (ddr3_ctrl_amm_0_agent_m0_burstcount),              //  output,   width = 12,                .burstcount
		.m0_byteenable           (ddr3_ctrl_amm_0_agent_m0_byteenable),              //  output,   width = 32,                .byteenable
		.m0_debugaccess          (ddr3_ctrl_amm_0_agent_m0_debugaccess),             //  output,    width = 1,                .debugaccess
		.m0_lock                 (ddr3_ctrl_amm_0_agent_m0_lock),                    //  output,    width = 1,                .lock
		.m0_readdata             (ddr3_ctrl_amm_0_agent_m0_readdata),                //   input,  width = 256,                .readdata
		.m0_readdatavalid        (ddr3_ctrl_amm_0_agent_m0_readdatavalid),           //   input,    width = 1,                .readdatavalid
		.m0_read                 (ddr3_ctrl_amm_0_agent_m0_read),                    //  output,    width = 1,                .read
		.m0_waitrequest          (ddr3_ctrl_amm_0_agent_m0_waitrequest),             //   input,    width = 1,                .waitrequest
		.m0_writedata            (ddr3_ctrl_amm_0_agent_m0_writedata),               //  output,  width = 256,                .writedata
		.m0_write                (ddr3_ctrl_amm_0_agent_m0_write),                   //  output,    width = 1,                .write
		.rp_endofpacket          (ddr3_ctrl_amm_0_agent_rp_endofpacket),             //  output,    width = 1,              rp.endofpacket
		.rp_ready                (ddr3_ctrl_amm_0_agent_rp_ready),                   //   input,    width = 1,                .ready
		.rp_valid                (ddr3_ctrl_amm_0_agent_rp_valid),                   //  output,    width = 1,                .valid
		.rp_data                 (ddr3_ctrl_amm_0_agent_rp_data),                    //  output,  width = 371,                .data
		.rp_startofpacket        (ddr3_ctrl_amm_0_agent_rp_startofpacket),           //  output,    width = 1,                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                                //  output,    width = 1,              cp.ready
		.cp_valid                (cmd_mux_src_valid),                                //   input,    width = 1,                .valid
		.cp_data                 (cmd_mux_src_data),                                 //   input,  width = 371,                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                        //   input,    width = 1,                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                          //   input,    width = 1,                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                              //   input,    width = 1,                .channel
		.rf_sink_ready           (ddr3_ctrl_amm_0_agent_rsp_fifo_out_ready),         //  output,    width = 1,         rf_sink.ready
		.rf_sink_valid           (ddr3_ctrl_amm_0_agent_rsp_fifo_out_valid),         //   input,    width = 1,                .valid
		.rf_sink_startofpacket   (ddr3_ctrl_amm_0_agent_rsp_fifo_out_startofpacket), //   input,    width = 1,                .startofpacket
		.rf_sink_endofpacket     (ddr3_ctrl_amm_0_agent_rsp_fifo_out_endofpacket),   //   input,    width = 1,                .endofpacket
		.rf_sink_data            (ddr3_ctrl_amm_0_agent_rsp_fifo_out_data),          //   input,  width = 372,                .data
		.rf_source_ready         (ddr3_ctrl_amm_0_agent_rf_source_ready),            //   input,    width = 1,       rf_source.ready
		.rf_source_valid         (ddr3_ctrl_amm_0_agent_rf_source_valid),            //  output,    width = 1,                .valid
		.rf_source_startofpacket (ddr3_ctrl_amm_0_agent_rf_source_startofpacket),    //  output,    width = 1,                .startofpacket
		.rf_source_endofpacket   (ddr3_ctrl_amm_0_agent_rf_source_endofpacket),      //  output,    width = 1,                .endofpacket
		.rf_source_data          (ddr3_ctrl_amm_0_agent_rf_source_data),             //  output,  width = 372,                .data
		.rdata_fifo_sink_ready   (ddr3_ctrl_amm_0_agent_rdata_fifo_src_ready),       //  output,    width = 1, rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (ddr3_ctrl_amm_0_agent_rdata_fifo_src_valid),       //   input,    width = 1,                .valid
		.rdata_fifo_sink_data    (ddr3_ctrl_amm_0_agent_rdata_fifo_src_data),        //   input,  width = 258,                .data
		.rdata_fifo_src_ready    (ddr3_ctrl_amm_0_agent_rdata_fifo_src_ready),       //   input,    width = 1,  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (ddr3_ctrl_amm_0_agent_rdata_fifo_src_valid),       //  output,    width = 1,                .valid
		.rdata_fifo_src_data     (ddr3_ctrl_amm_0_agent_rdata_fifo_src_data),        //  output,  width = 258,                .data
		.m0_response             (2'b00),                                            // (terminated),                               
		.m0_writeresponsevalid   (1'b0),                                             // (terminated),                               
		.rdata_fifo_sink_error   (1'b0)                                              // (terminated),                               
	);

	mcu_subsystem_altera_avalon_sc_fifo_181_oywqgnq #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (372),
		.FIFO_DEPTH          (65),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0),
		.SYNC_RESET          (0)
	) ddr3_ctrl_amm_0_agent_rsp_fifo (
		.clk               (ddr3_emif_usr_clk_clk),                            //   input,    width = 1,       clk.clk
		.reset             (bridge_0_m0_reset_reset_bridge_in_reset_reset),    //   input,    width = 1, clk_reset.reset
		.in_data           (ddr3_ctrl_amm_0_agent_rf_source_data),             //   input,  width = 372,        in.data
		.in_valid          (ddr3_ctrl_amm_0_agent_rf_source_valid),            //   input,    width = 1,          .valid
		.in_ready          (ddr3_ctrl_amm_0_agent_rf_source_ready),            //  output,    width = 1,          .ready
		.in_startofpacket  (ddr3_ctrl_amm_0_agent_rf_source_startofpacket),    //   input,    width = 1,          .startofpacket
		.in_endofpacket    (ddr3_ctrl_amm_0_agent_rf_source_endofpacket),      //   input,    width = 1,          .endofpacket
		.out_data          (ddr3_ctrl_amm_0_agent_rsp_fifo_out_data),          //  output,  width = 372,       out.data
		.out_valid         (ddr3_ctrl_amm_0_agent_rsp_fifo_out_valid),         //  output,    width = 1,          .valid
		.out_ready         (ddr3_ctrl_amm_0_agent_rsp_fifo_out_ready),         //   input,    width = 1,          .ready
		.out_startofpacket (ddr3_ctrl_amm_0_agent_rsp_fifo_out_startofpacket), //  output,    width = 1,          .startofpacket
		.out_endofpacket   (ddr3_ctrl_amm_0_agent_rsp_fifo_out_endofpacket),   //  output,    width = 1,          .endofpacket
		.csr_address       (2'b00),                                            // (terminated),                         
		.csr_read          (1'b0),                                             // (terminated),                         
		.csr_write         (1'b0),                                             // (terminated),                         
		.csr_readdata      (),                                                 // (terminated),                         
		.csr_writedata     (32'b00000000000000000000000000000000),             // (terminated),                         
		.almost_full_data  (),                                                 // (terminated),                         
		.almost_empty_data (),                                                 // (terminated),                         
		.in_empty          (1'b0),                                             // (terminated),                         
		.out_empty         (),                                                 // (terminated),                         
		.in_error          (1'b0),                                             // (terminated),                         
		.out_error         (),                                                 // (terminated),                         
		.in_channel        (1'b0),                                             // (terminated),                         
		.out_channel       ()                                                  // (terminated),                         
	);

	mcu_subsystem_altera_merlin_router_181_yegeldy router (
		.sink_ready         (bridge_0_m0_agent_cp_ready),                    //  output,    width = 1,      sink.ready
		.sink_valid         (bridge_0_m0_agent_cp_valid),                    //   input,    width = 1,          .valid
		.sink_data          (bridge_0_m0_agent_cp_data),                     //   input,  width = 371,          .data
		.sink_startofpacket (bridge_0_m0_agent_cp_startofpacket),            //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (bridge_0_m0_agent_cp_endofpacket),              //   input,    width = 1,          .endofpacket
		.clk                (ddr3_emif_usr_clk_clk),                         //   input,    width = 1,       clk.clk
		.reset              (bridge_0_m0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_src_ready),                              //   input,    width = 1,       src.ready
		.src_valid          (router_src_valid),                              //  output,    width = 1,          .valid
		.src_data           (router_src_data),                               //  output,  width = 371,          .data
		.src_channel        (router_src_channel),                            //  output,    width = 1,          .channel
		.src_startofpacket  (router_src_startofpacket),                      //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                         //  output,    width = 1,          .endofpacket
	);

	mcu_subsystem_altera_merlin_router_181_znjx25i router_001 (
		.sink_ready         (ddr3_ctrl_amm_0_agent_rp_ready),                //  output,    width = 1,      sink.ready
		.sink_valid         (ddr3_ctrl_amm_0_agent_rp_valid),                //   input,    width = 1,          .valid
		.sink_data          (ddr3_ctrl_amm_0_agent_rp_data),                 //   input,  width = 371,          .data
		.sink_startofpacket (ddr3_ctrl_amm_0_agent_rp_startofpacket),        //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (ddr3_ctrl_amm_0_agent_rp_endofpacket),          //   input,    width = 1,          .endofpacket
		.clk                (ddr3_emif_usr_clk_clk),                         //   input,    width = 1,       clk.clk
		.reset              (bridge_0_m0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready          (router_001_src_ready),                          //   input,    width = 1,       src.ready
		.src_valid          (router_001_src_valid),                          //  output,    width = 1,          .valid
		.src_data           (router_001_src_data),                           //  output,  width = 371,          .data
		.src_channel        (router_001_src_channel),                        //  output,    width = 1,          .channel
		.src_startofpacket  (router_001_src_startofpacket),                  //  output,    width = 1,          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                     //  output,    width = 1,          .endofpacket
	);

	mcu_subsystem_altera_merlin_demultiplexer_181_aomhf3y cmd_demux (
		.clk                (ddr3_emif_usr_clk_clk),                         //   input,    width = 1,       clk.clk
		.reset              (bridge_0_m0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_src_ready),                              //  output,    width = 1,      sink.ready
		.sink_channel       (router_src_channel),                            //   input,    width = 1,          .channel
		.sink_data          (router_src_data),                               //   input,  width = 371,          .data
		.sink_startofpacket (router_src_startofpacket),                      //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                        //   input,    width = 1,          .endofpacket
		.sink_valid         (router_src_valid),                              //   input,    width = 1,          .valid
		.src0_ready         (cmd_demux_src0_ready),                          //   input,    width = 1,      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                          //  output,    width = 1,          .valid
		.src0_data          (cmd_demux_src0_data),                           //  output,  width = 371,          .data
		.src0_channel       (cmd_demux_src0_channel),                        //  output,    width = 1,          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                  //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket)                     //  output,    width = 1,          .endofpacket
	);

	mcu_subsystem_altera_merlin_multiplexer_181_njgnuha cmd_mux (
		.clk                 (ddr3_emif_usr_clk_clk),                         //   input,    width = 1,       clk.clk
		.reset               (bridge_0_m0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                             //   input,    width = 1,       src.ready
		.src_valid           (cmd_mux_src_valid),                             //  output,    width = 1,          .valid
		.src_data            (cmd_mux_src_data),                              //  output,  width = 371,          .data
		.src_channel         (cmd_mux_src_channel),                           //  output,    width = 1,          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                     //  output,    width = 1,          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                       //  output,    width = 1,          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                          //  output,    width = 1,     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                          //   input,    width = 1,          .valid
		.sink0_channel       (cmd_demux_src0_channel),                        //   input,    width = 1,          .channel
		.sink0_data          (cmd_demux_src0_data),                           //   input,  width = 371,          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                  //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                     //   input,    width = 1,          .endofpacket
	);

	mcu_subsystem_altera_merlin_demultiplexer_181_aomhf3y rsp_demux (
		.clk                (ddr3_emif_usr_clk_clk),                         //   input,    width = 1,       clk.clk
		.reset              (bridge_0_m0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.sink_ready         (router_001_src_ready),                          //  output,    width = 1,      sink.ready
		.sink_channel       (router_001_src_channel),                        //   input,    width = 1,          .channel
		.sink_data          (router_001_src_data),                           //   input,  width = 371,          .data
		.sink_startofpacket (router_001_src_startofpacket),                  //   input,    width = 1,          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                    //   input,    width = 1,          .endofpacket
		.sink_valid         (router_001_src_valid),                          //   input,    width = 1,          .valid
		.src0_ready         (rsp_demux_src0_ready),                          //   input,    width = 1,      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                          //  output,    width = 1,          .valid
		.src0_data          (rsp_demux_src0_data),                           //  output,  width = 371,          .data
		.src0_channel       (rsp_demux_src0_channel),                        //  output,    width = 1,          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                  //  output,    width = 1,          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                     //  output,    width = 1,          .endofpacket
	);

	mcu_subsystem_altera_merlin_multiplexer_181_32pwj5q rsp_mux (
		.clk                 (ddr3_emif_usr_clk_clk),                         //   input,    width = 1,       clk.clk
		.reset               (bridge_0_m0_reset_reset_bridge_in_reset_reset), //   input,    width = 1, clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                             //   input,    width = 1,       src.ready
		.src_valid           (rsp_mux_src_valid),                             //  output,    width = 1,          .valid
		.src_data            (rsp_mux_src_data),                              //  output,  width = 371,          .data
		.src_channel         (rsp_mux_src_channel),                           //  output,    width = 1,          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                     //  output,    width = 1,          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                       //  output,    width = 1,          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                          //  output,    width = 1,     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                          //   input,    width = 1,          .valid
		.sink0_channel       (rsp_demux_src0_channel),                        //   input,    width = 1,          .channel
		.sink0_data          (rsp_demux_src0_data),                           //   input,  width = 371,          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                  //   input,    width = 1,          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket)                     //   input,    width = 1,          .endofpacket
	);

endmodule
