cat >conf19464subs.awk <<_ACEOF
am__EXEEXT_FALSE!$am__EXEEXT_FALSE$ac_delim
am__EXEEXT_TRUE!$am__EXEEXT_TRUE$ac_delim
LTLIBOBJS!$LTLIBOBJS$ac_delim
LIBOBJS!$LIBOBJS$ac_delim
HAVE_MACHINE_DIR_FALSE!$HAVE_MACHINE_DIR_FALSE$ac_delim
HAVE_MACHINE_DIR_TRUE!$HAVE_MACHINE_DIR_TRUE$ac_delim
subdirs!$subdirs$ac_delim
CPP!$CPP$ac_delim
OTOOL64!$OTOOL64$ac_delim
OTOOL!$OTOOL$ac_delim
LIPO!$LIPO$ac_delim
NMEDIT!$NMEDIT$ac_delim
DSYMUTIL!$DSYMUTIL$ac_delim
LN_S!$LN_S$ac_delim
NM!$NM$ac_delim
ac_ct_DUMPBIN!$ac_ct_DUMPBIN$ac_delim
DUMPBIN!$DUMPBIN$ac_delim
LD!$LD$ac_delim
FGREP!$FGREP$ac_delim
EGREP!$EGREP$ac_delim
GREP!$GREP$ac_delim
EXEEXT!$EXEEXT$ac_delim
ac_ct_CC!$ac_ct_CC$ac_delim
CPPFLAGS!$CPPFLAGS$ac_delim
CFLAGS!$CFLAGS$ac_delim
LIBTOOL!$LIBTOOL$ac_delim
OBJDUMP!$OBJDUMP$ac_delim
DLLTOOL!$DLLTOOL$ac_delim
SED!$SED$ac_delim
sys_dir!$sys_dir$ac_delim
machine_dir!$machine_dir$ac_delim
libm_machine_dir!$libm_machine_dir$ac_delim
lpfx!$lpfx$ac_delim
aext!$aext$ac_delim
oext!$oext$ac_delim
OBJEXT!$OBJEXT$ac_delim
USE_LIBTOOL_FALSE!$USE_LIBTOOL_FALSE$ac_delim
USE_LIBTOOL_TRUE!$USE_LIBTOOL_TRUE$ac_delim
ELIX_LEVEL_4_FALSE!$ELIX_LEVEL_4_FALSE$ac_delim
ELIX_LEVEL_4_TRUE!$ELIX_LEVEL_4_TRUE$ac_delim
ELIX_LEVEL_3_FALSE!$ELIX_LEVEL_3_FALSE$ac_delim
ELIX_LEVEL_3_TRUE!$ELIX_LEVEL_3_TRUE$ac_delim
ELIX_LEVEL_2_FALSE!$ELIX_LEVEL_2_FALSE$ac_delim
ELIX_LEVEL_2_TRUE!$ELIX_LEVEL_2_TRUE$ac_delim
ELIX_LEVEL_1_FALSE!$ELIX_LEVEL_1_FALSE$ac_delim
ELIX_LEVEL_1_TRUE!$ELIX_LEVEL_1_TRUE$ac_delim
ELIX_LEVEL_0_FALSE!$ELIX_LEVEL_0_FALSE$ac_delim
ELIX_LEVEL_0_TRUE!$ELIX_LEVEL_0_TRUE$ac_delim
LDFLAGS!$LDFLAGS$ac_delim
NO_INCLUDE_LIST!$NO_INCLUDE_LIST$ac_delim
NEWLIB_CFLAGS!$NEWLIB_CFLAGS$ac_delim
CCASFLAGS!$CCASFLAGS$ac_delim
CCAS!$CCAS$ac_delim
MAINT!$MAINT$ac_delim
MAINTAINER_MODE_FALSE!$MAINTAINER_MODE_FALSE$ac_delim
MAINTAINER_MODE_TRUE!$MAINTAINER_MODE_TRUE$ac_delim
READELF!$READELF$ac_delim
RANLIB!$RANLIB$ac_delim
AR!$AR$ac_delim
AS!$AS$ac_delim
am__fastdepCC_FALSE!$am__fastdepCC_FALSE$ac_delim
am__fastdepCC_TRUE!$am__fastdepCC_TRUE$ac_delim
CCDEPMODE!$CCDEPMODE$ac_delim
am__nodep!$am__nodep$ac_delim
AMDEPBACKSLASH!$AMDEPBACKSLASH$ac_delim
AMDEP_FALSE!$AMDEP_FALSE$ac_delim
AMDEP_TRUE!$AMDEP_TRUE$ac_delim
am__quote!$am__quote$ac_delim
am__include!$am__include$ac_delim
DEPDIR!$DEPDIR$ac_delim
CC!$CC$ac_delim
am__untar!$am__untar$ac_delim
am__tar!$am__tar$ac_delim
AMTAR!$AMTAR$ac_delim
am__leading_dot!$am__leading_dot$ac_delim
SET_MAKE!$SET_MAKE$ac_delim
AWK!$AWK$ac_delim
mkdir_p!$mkdir_p$ac_delim
MKDIR_P!$MKDIR_P$ac_delim
INSTALL_STRIP_PROGRAM!$INSTALL_STRIP_PROGRAM$ac_delim
STRIP!$STRIP$ac_delim
install_sh!$install_sh$ac_delim
MAKEINFO!$MAKEINFO$ac_delim
AUTOHEADER!$AUTOHEADER$ac_delim
AUTOMAKE!$AUTOMAKE$ac_delim
AUTOCONF!$AUTOCONF$ac_delim
ACLOCAL!$ACLOCAL$ac_delim
VERSION!$VERSION$ac_delim
PACKAGE!$PACKAGE$ac_delim
CYGPATH_W!$CYGPATH_W$ac_delim
am__isrc!$am__isrc$ac_delim
INSTALL_DATA!$INSTALL_DATA$ac_delim
INSTALL_SCRIPT!$INSTALL_SCRIPT$ac_delim
INSTALL_PROGRAM!$INSTALL_PROGRAM$ac_delim
host_os!$host_os$ac_delim
host_vendor!$host_vendor$ac_delim
host_cpu!$host_cpu$ac_delim
host!$host$ac_delim
build_os!$build_os$ac_delim
build_vendor!$build_vendor$ac_delim
build_cpu!$build_cpu$ac_delim
build!$build$ac_delim
newlib_basedir!$newlib_basedir$ac_delim
MAY_SUPPLY_SYSCALLS_FALSE!$MAY_SUPPLY_SYSCALLS_FALSE$ac_delim
MAY_SUPPLY_SYSCALLS_TRUE!$MAY_SUPPLY_SYSCALLS_TRUE$ac_delim
target_alias!$target_alias$ac_delim
host_alias!$host_alias$ac_delim
build_alias!$build_alias$ac_delim
LIBS!$LIBS$ac_delim
ECHO_T!$ECHO_T$ac_delim
ECHO_N!$ECHO_N$ac_delim
ECHO_C!$ECHO_C$ac_delim
DEFS!$DEFS$ac_delim
mandir!$mandir$ac_delim
localedir!$localedir$ac_delim
libdir!$libdir$ac_delim
psdir!$psdir$ac_delim
pdfdir!$pdfdir$ac_delim
dvidir!$dvidir$ac_delim
htmldir!$htmldir$ac_delim
infodir!$infodir$ac_delim
docdir!$docdir$ac_delim
oldincludedir!$oldincludedir$ac_delim
includedir!$includedir$ac_delim
localstatedir!$localstatedir$ac_delim
sharedstatedir!$sharedstatedir$ac_delim
sysconfdir!$sysconfdir$ac_delim
datadir!$datadir$ac_delim
datarootdir!$datarootdir$ac_delim
libexecdir!$libexecdir$ac_delim
sbindir!$sbindir$ac_delim
bindir!$bindir$ac_delim
program_transform_name!$program_transform_name$ac_delim
prefix!$prefix$ac_delim
exec_prefix!$exec_prefix$ac_delim
PACKAGE_URL!$PACKAGE_URL$ac_delim
PACKAGE_BUGREPORT!$PACKAGE_BUGREPORT$ac_delim
PACKAGE_STRING!$PACKAGE_STRING$ac_delim
PACKAGE_VERSION!$PACKAGE_VERSION$ac_delim
PACKAGE_TARNAME!$PACKAGE_TARNAME$ac_delim
PACKAGE_NAME!$PACKAGE_NAME$ac_delim
PATH_SEPARATOR!$PATH_SEPARATOR$ac_delim
SHELL!$SHELL$ac_delim
_ACEOF
