config system_bd_altera_arria10_hps_io_181_fbqmexy_cfg;
		design system_bd_altera_arria10_hps_io_181_fbqmexy;
		instance system_bd_altera_arria10_hps_io_181_fbqmexy.border use system_bd_altera_arria10_interface_generator_140.system_bd_altera_arria10_interface_generator_140_nuexhka;
endconfig

