config system_bd_altera_avalon_st_adapter_181_e7v4oka_cfg;
		design system_bd_altera_avalon_st_adapter_181_e7v4oka;
		instance system_bd_altera_avalon_st_adapter_181_e7v4oka.error_adapter_0 use system_bd_error_adapter_181.system_bd_error_adapter_181_tmmt7mq;
endconfig

