config system_bd_altera_avalon_st_adapter_181_25xtenq_cfg;
		design system_bd_altera_avalon_st_adapter_181_25xtenq;
		instance system_bd_altera_avalon_st_adapter_181_25xtenq.error_adapter_0 use system_bd_error_adapter_181.system_bd_error_adapter_181_6bjmpii;
endconfig

