config system_bd_altera_avalon_st_adapter_181_qpygkyi_cfg;
		design system_bd_altera_avalon_st_adapter_181_qpygkyi;
		instance system_bd_altera_avalon_st_adapter_181_qpygkyi.data_format_adapter_0 use system_bd_data_format_adapter_181.system_bd_data_format_adapter_181_3mviboq;
		instance system_bd_altera_avalon_st_adapter_181_qpygkyi.timing_adapter_0 use system_bd_timing_adapter_181.system_bd_timing_adapter_181_3cdoppq;
endconfig

