// mcu_subsystem_util_adcfifo_0_alt_mem_asym_10_ngt5uda.v

// This file was auto-generated from alt_mem_asym_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1.2 277

`timescale 1 ps / 1 ps
module mcu_subsystem_util_adcfifo_0_alt_mem_asym_10_ngt5uda #(
		parameter A_ADDRESS_WIDTH = 0,
		parameter A_DATA_WIDTH    = 128,
		parameter B_ADDRESS_WIDTH = 10,
		parameter B_DATA_WIDTH    = 128
	) (
		input  wire [127:0] data_datain,         //      data.datain
		output wire [127:0] mem_o_dataout,       //     mem_o.dataout
		input  wire [9:0]   wraddress_wraddress, // wraddress.wraddress
		input  wire [9:0]   rdaddress_rdaddress, // rdaddress.rdaddress
		input  wire         wren_wren,           //      wren.wren
		input  wire         wrclock_clk,         //   wrclock.clk
		input  wire         rdclock_clk          //   rdclock.clk
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (A_ADDRESS_WIDTH != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					a_address_width_check ( .error(1'b1) );
		end
		if (A_DATA_WIDTH != 128)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					a_data_width_check ( .error(1'b1) );
		end
		if (B_ADDRESS_WIDTH != 10)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					b_address_width_check ( .error(1'b1) );
		end
		if (B_DATA_WIDTH != 128)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					b_data_width_check ( .error(1'b1) );
		end
	endgenerate

	mcu_subsystem_util_adcfifo_0_ram_2port_181_5dibq2a alt_mem (
		.data      (data_datain),         //   input,  width = 128,      data.datain
		.q         (mem_o_dataout),       //  output,  width = 128,         q.dataout
		.wraddress (wraddress_wraddress), //   input,   width = 10, wraddress.wraddress
		.rdaddress (rdaddress_rdaddress), //   input,   width = 10, rdaddress.rdaddress
		.wren      (wren_wren),           //   input,    width = 1,      wren.wren
		.wrclock   (wrclock_clk),         //   input,    width = 1,   wrclock.clk
		.rdclock   (rdclock_clk)          //   input,    width = 1,   rdclock.clk
	);

endmodule
