config system_bd_altera_mm_interconnect_181_aa7z3hi_cfg;
		design system_bd_altera_mm_interconnect_181_aa7z3hi;
		instance system_bd_altera_mm_interconnect_181_aa7z3hi.ioaux_master_bridge_m0_translator use system_bd_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance system_bd_altera_mm_interconnect_181_aa7z3hi.ioaux_soft_ram_s1_translator use system_bd_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
endconfig

