	system_bd u0 (
		.rx_ref_clk_clk                 (<connected-to-rx_ref_clk_clk>),                 //                 rx_ref_clk.clk
		.rx_serial_data_rx_serial_data  (<connected-to-rx_serial_data_rx_serial_data>),  //             rx_serial_data.rx_serial_data
		.rx_sync_export                 (<connected-to-rx_sync_export>),                 //                    rx_sync.export
		.rx_sysref_export               (<connected-to-rx_sysref_export>),               //                  rx_sysref.export
		.sys_clk_clk                    (<connected-to-sys_clk_clk>),                    //                    sys_clk.clk
		.sys_ddr3_cntrl_mem_mem_ck      (<connected-to-sys_ddr3_cntrl_mem_mem_ck>),      //         sys_ddr3_cntrl_mem.mem_ck
		.sys_ddr3_cntrl_mem_mem_ck_n    (<connected-to-sys_ddr3_cntrl_mem_mem_ck_n>),    //                           .mem_ck_n
		.sys_ddr3_cntrl_mem_mem_a       (<connected-to-sys_ddr3_cntrl_mem_mem_a>),       //                           .mem_a
		.sys_ddr3_cntrl_mem_mem_ba      (<connected-to-sys_ddr3_cntrl_mem_mem_ba>),      //                           .mem_ba
		.sys_ddr3_cntrl_mem_mem_cke     (<connected-to-sys_ddr3_cntrl_mem_mem_cke>),     //                           .mem_cke
		.sys_ddr3_cntrl_mem_mem_cs_n    (<connected-to-sys_ddr3_cntrl_mem_mem_cs_n>),    //                           .mem_cs_n
		.sys_ddr3_cntrl_mem_mem_odt     (<connected-to-sys_ddr3_cntrl_mem_mem_odt>),     //                           .mem_odt
		.sys_ddr3_cntrl_mem_mem_reset_n (<connected-to-sys_ddr3_cntrl_mem_mem_reset_n>), //                           .mem_reset_n
		.sys_ddr3_cntrl_mem_mem_we_n    (<connected-to-sys_ddr3_cntrl_mem_mem_we_n>),    //                           .mem_we_n
		.sys_ddr3_cntrl_mem_mem_ras_n   (<connected-to-sys_ddr3_cntrl_mem_mem_ras_n>),   //                           .mem_ras_n
		.sys_ddr3_cntrl_mem_mem_cas_n   (<connected-to-sys_ddr3_cntrl_mem_mem_cas_n>),   //                           .mem_cas_n
		.sys_ddr3_cntrl_mem_mem_dqs     (<connected-to-sys_ddr3_cntrl_mem_mem_dqs>),     //                           .mem_dqs
		.sys_ddr3_cntrl_mem_mem_dqs_n   (<connected-to-sys_ddr3_cntrl_mem_mem_dqs_n>),   //                           .mem_dqs_n
		.sys_ddr3_cntrl_mem_mem_dq      (<connected-to-sys_ddr3_cntrl_mem_mem_dq>),      //                           .mem_dq
		.sys_ddr3_cntrl_mem_mem_dm      (<connected-to-sys_ddr3_cntrl_mem_mem_dm>),      //                           .mem_dm
		.sys_ddr3_cntrl_oct_oct_rzqin   (<connected-to-sys_ddr3_cntrl_oct_oct_rzqin>),   //         sys_ddr3_cntrl_oct.oct_rzqin
		.sys_ddr3_cntrl_pll_ref_clk_clk (<connected-to-sys_ddr3_cntrl_pll_ref_clk_clk>), // sys_ddr3_cntrl_pll_ref_clk.clk
		.sys_ethernet_mdio_mdc          (<connected-to-sys_ethernet_mdio_mdc>),          //          sys_ethernet_mdio.mdc
		.sys_ethernet_mdio_mdio_in      (<connected-to-sys_ethernet_mdio_mdio_in>),      //                           .mdio_in
		.sys_ethernet_mdio_mdio_out     (<connected-to-sys_ethernet_mdio_mdio_out>),     //                           .mdio_out
		.sys_ethernet_mdio_mdio_oen     (<connected-to-sys_ethernet_mdio_mdio_oen>),     //                           .mdio_oen
		.sys_ethernet_ref_clk_clk       (<connected-to-sys_ethernet_ref_clk_clk>),       //       sys_ethernet_ref_clk.clk
		.sys_ethernet_reset_reset       (<connected-to-sys_ethernet_reset_reset>),       //         sys_ethernet_reset.reset
		.sys_ethernet_sgmii_rxp_0       (<connected-to-sys_ethernet_sgmii_rxp_0>),       //         sys_ethernet_sgmii.rxp_0
		.sys_ethernet_sgmii_txp_0       (<connected-to-sys_ethernet_sgmii_txp_0>),       //                           .txp_0
		.sys_flash_tcm_address_out      (<connected-to-sys_flash_tcm_address_out>),      //                  sys_flash.tcm_address_out
		.sys_flash_tcm_read_n_out       (<connected-to-sys_flash_tcm_read_n_out>),       //                           .tcm_read_n_out
		.sys_flash_tcm_write_n_out      (<connected-to-sys_flash_tcm_write_n_out>),      //                           .tcm_write_n_out
		.sys_flash_tcm_data_out         (<connected-to-sys_flash_tcm_data_out>),         //                           .tcm_data_out
		.sys_flash_tcm_chipselect_n_out (<connected-to-sys_flash_tcm_chipselect_n_out>), //                           .tcm_chipselect_n_out
		.sys_gpio_bd_in_port            (<connected-to-sys_gpio_bd_in_port>),            //                sys_gpio_bd.in_port
		.sys_gpio_bd_out_port           (<connected-to-sys_gpio_bd_out_port>),           //                           .out_port
		.sys_gpio_in_export             (<connected-to-sys_gpio_in_export>),             //                sys_gpio_in.export
		.sys_gpio_out_export            (<connected-to-sys_gpio_out_export>),            //               sys_gpio_out.export
		.sys_rst_reset_n                (<connected-to-sys_rst_reset_n>),                //                    sys_rst.reset_n
		.sys_spi_MISO                   (<connected-to-sys_spi_MISO>),                   //                    sys_spi.MISO
		.sys_spi_MOSI                   (<connected-to-sys_spi_MOSI>),                   //                           .MOSI
		.sys_spi_SCLK                   (<connected-to-sys_spi_SCLK>),                   //                           .SCLK
		.sys_spi_SS_n                   (<connected-to-sys_spi_SS_n>),                   //                           .SS_n
		.tx_fifo_bypass_bypass          (<connected-to-tx_fifo_bypass_bypass>),          //             tx_fifo_bypass.bypass
		.tx_ref_clk_clk                 (<connected-to-tx_ref_clk_clk>),                 //                 tx_ref_clk.clk
		.tx_serial_data_tx_serial_data  (<connected-to-tx_serial_data_tx_serial_data>),  //             tx_serial_data.tx_serial_data
		.tx_sync_export                 (<connected-to-tx_sync_export>),                 //                    tx_sync.export
		.tx_sysref_export               (<connected-to-tx_sysref_export>)                //                  tx_sysref.export
	);

