config alt_sld_fab_alt_sld_fab_181_ss6a2vq_cfg;
		design alt_sld_fab_alt_sld_fab_181_ss6a2vq;
		instance alt_sld_fab_alt_sld_fab_181_ss6a2vq.presplit use alt_sld_fab_altera_super_splitter_181.alt_sld_fab_altera_super_splitter_181_v2qgfvq;
		instance alt_sld_fab_alt_sld_fab_181_ss6a2vq.splitter use alt_sld_fab_altera_sld_splitter_181.alt_sld_fab_altera_sld_splitter_181_hdtscuq;
		instance alt_sld_fab_alt_sld_fab_181_ss6a2vq.sldfabric use alt_sld_fab_altera_sld_jtag_hub_181.alt_sld_fab_altera_sld_jtag_hub_181_rb27pbq;
		instance alt_sld_fab_alt_sld_fab_181_ss6a2vq.ident use alt_sld_fab_altera_connection_identification_hub_181.alt_sld_fab_altera_connection_identification_hub_181_z6kqx7a;
		instance alt_sld_fab_alt_sld_fab_181_ss6a2vq.a10xcvrfabric use alt_sld_fab_altera_a10_xcvr_reset_sequencer_181.alt_sld_fab_altera_a10_xcvr_reset_sequencer_181_ivi4soy;
endconfig

