config system_bd_altera_emif_a10_hps_181_fyxkrly_cfg;
		design system_bd_altera_emif_a10_hps_181_fyxkrly;
		instance system_bd_altera_emif_a10_hps_181_fyxkrly.arch use system_bd_altera_emif_arch_nf_181.system_bd_altera_emif_arch_nf_181_gsbdrhy;
endconfig

