set_global_assignment -name IP_FILE ip/mcu_subsystem/ddr_controller.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_jtag_uart_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_reset_in.ip
set_global_assignment -name IP_FILE ip/interlaken_phy/interlaken_phy_clock_bridge_0.ip
set_global_assignment -name IP_FILE ip/interlaken_phy/interlaken_phy_xcvr_atx_pll_a10_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/iopll_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_timer_1.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_timer_0.ip
set_global_assignment -name IP_FILE ip/interlaken_phy/interlaken_phy_xcvr_data_flow_controller_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_cpu_0.ip
set_global_assignment -name IP_FILE ip/interlaken_phy/interlaken_phy_xcvr_native_a10_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_mm_clock_crossing_bridge_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_clock_in.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_reset_bridge_0.ip
set_global_assignment -name IP_FILE ip/interlaken_phy/interlaken_phy_xcvr_reset_control_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_mm_clock_crossing_bridge_3.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_generic_quad_spi_controller2_0.ip
set_global_assignment -name IP_FILE ip/interlaken_phy/interlaken_phy_reset_bridge_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_mm_clock_crossing_bridge_1.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_clock_bridge_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_mm_clock_crossing_bridge_2.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_ram_0.ip
set_global_assignment -name IP_FILE ip/mcu_subsystem/mcu_subsystem_clock_bridge_1.ip
