# TCL File Generated by Component Editor 18.1.2
# Tue Jun 04 14:57:16 CEST 2019
# DO NOT MODIFY


# 
# xcvr_data_flow_controller "Transceiver Native PHY Data Flow Controller" v1.0
# Rafal M. Gisko 2019.06.04.14:57:16
# 
# 

# 
# request TCL package from ACDS 19.1
# 
package require -exact qsys 19.1


# 
# module xcvr_data_flow_controller
# 
set_module_property DESCRIPTION ""
set_module_property NAME xcvr_data_flow_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Rafal M. Gisko"
set_module_property DISPLAY_NAME "Transceiver Native PHY Data Flow Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL xcvr_data_flow_controller
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file xcvr_data_flow_controller.v VERILOG PATH xcvr_data_flow_controller.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point csr_s0
# 
add_interface csr_s0 avalon end
set_interface_property csr_s0 addressGroup 0
set_interface_property csr_s0 addressUnits WORDS
set_interface_property csr_s0 associatedClock clk
set_interface_property csr_s0 associatedReset rst
set_interface_property csr_s0 bitsPerSymbol 8
set_interface_property csr_s0 bridgedAddressOffset 0
set_interface_property csr_s0 bridgesToMaster ""
set_interface_property csr_s0 burstOnBurstBoundariesOnly false
set_interface_property csr_s0 burstcountUnits WORDS
set_interface_property csr_s0 explicitAddressSpan 0
set_interface_property csr_s0 holdTime 0
set_interface_property csr_s0 linewrapBursts false
set_interface_property csr_s0 maximumPendingReadTransactions 1
set_interface_property csr_s0 maximumPendingWriteTransactions 0
set_interface_property csr_s0 minimumResponseLatency 1
set_interface_property csr_s0 readLatency 0
set_interface_property csr_s0 readWaitTime 1
set_interface_property csr_s0 setupTime 0
set_interface_property csr_s0 timingUnits Cycles
set_interface_property csr_s0 transparentBridge false
set_interface_property csr_s0 waitrequestAllowance 0
set_interface_property csr_s0 writeWaitTime 0
set_interface_property csr_s0 ENABLED true
set_interface_property csr_s0 EXPORT_OF ""
set_interface_property csr_s0 PORT_NAME_MAP ""
set_interface_property csr_s0 CMSIS_SVD_VARIABLES ""
set_interface_property csr_s0 SVD_ADDRESS_GROUP ""
set_interface_property csr_s0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port csr_s0 csr_s0_address address Input 8
add_interface_port csr_s0 csr_s0_read read Input 1
add_interface_port csr_s0 csr_s0_readdata readdata Output 32
add_interface_port csr_s0 csr_s0_readdatavalid readdatavalid Output 1
add_interface_port csr_s0 csr_s0_write write Input 1
add_interface_port csr_s0 csr_s0_writedata writedata Input 32
add_interface_port csr_s0 csr_s0_waitrequest waitrequest Output 1
set_interface_assignment csr_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment csr_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment csr_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment csr_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point rx_parallel_data
# 
add_interface rx_parallel_data conduit end
set_interface_property rx_parallel_data associatedClock ""
set_interface_property rx_parallel_data associatedReset ""
set_interface_property rx_parallel_data ENABLED true
set_interface_property rx_parallel_data EXPORT_OF ""
set_interface_property rx_parallel_data PORT_NAME_MAP ""
set_interface_property rx_parallel_data CMSIS_SVD_VARIABLES ""
set_interface_property rx_parallel_data SVD_ADDRESS_GROUP ""
set_interface_property rx_parallel_data IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_parallel_data rx_parallel_data rx_parallel_data Input 64


# 
# connection point tx_parallel_data
# 
add_interface tx_parallel_data conduit end
set_interface_property tx_parallel_data associatedClock ""
set_interface_property tx_parallel_data associatedReset ""
set_interface_property tx_parallel_data ENABLED true
set_interface_property tx_parallel_data EXPORT_OF ""
set_interface_property tx_parallel_data PORT_NAME_MAP ""
set_interface_property tx_parallel_data CMSIS_SVD_VARIABLES ""
set_interface_property tx_parallel_data SVD_ADDRESS_GROUP ""
set_interface_property tx_parallel_data IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_parallel_data tx_parallel_data tx_parallel_data Output 64


# 
# connection point rx_enh_fifo_full
# 
add_interface rx_enh_fifo_full conduit end
set_interface_property rx_enh_fifo_full associatedClock ""
set_interface_property rx_enh_fifo_full associatedReset ""
set_interface_property rx_enh_fifo_full ENABLED true
set_interface_property rx_enh_fifo_full EXPORT_OF ""
set_interface_property rx_enh_fifo_full PORT_NAME_MAP ""
set_interface_property rx_enh_fifo_full CMSIS_SVD_VARIABLES ""
set_interface_property rx_enh_fifo_full SVD_ADDRESS_GROUP ""
set_interface_property rx_enh_fifo_full IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_enh_fifo_full rx_enh_fifo_full rx_enh_fifo_full Input 1


# 
# connection point rx_enh_fifo_pfull
# 
add_interface rx_enh_fifo_pfull conduit end
set_interface_property rx_enh_fifo_pfull associatedClock ""
set_interface_property rx_enh_fifo_pfull associatedReset ""
set_interface_property rx_enh_fifo_pfull ENABLED true
set_interface_property rx_enh_fifo_pfull EXPORT_OF ""
set_interface_property rx_enh_fifo_pfull PORT_NAME_MAP ""
set_interface_property rx_enh_fifo_pfull CMSIS_SVD_VARIABLES ""
set_interface_property rx_enh_fifo_pfull SVD_ADDRESS_GROUP ""
set_interface_property rx_enh_fifo_pfull IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_enh_fifo_pfull rx_enh_fifo_pfull rx_enh_fifo_pfull Input 1


# 
# connection point rx_enh_fifo_empty
# 
add_interface rx_enh_fifo_empty conduit end
set_interface_property rx_enh_fifo_empty associatedClock ""
set_interface_property rx_enh_fifo_empty associatedReset ""
set_interface_property rx_enh_fifo_empty ENABLED true
set_interface_property rx_enh_fifo_empty EXPORT_OF ""
set_interface_property rx_enh_fifo_empty PORT_NAME_MAP ""
set_interface_property rx_enh_fifo_empty CMSIS_SVD_VARIABLES ""
set_interface_property rx_enh_fifo_empty SVD_ADDRESS_GROUP ""
set_interface_property rx_enh_fifo_empty IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_enh_fifo_empty rx_enh_fifo_empty rx_enh_fifo_empty Input 1


# 
# connection point rx_enh_fifo_pempty
# 
add_interface rx_enh_fifo_pempty conduit end
set_interface_property rx_enh_fifo_pempty associatedClock ""
set_interface_property rx_enh_fifo_pempty associatedReset ""
set_interface_property rx_enh_fifo_pempty ENABLED true
set_interface_property rx_enh_fifo_pempty EXPORT_OF ""
set_interface_property rx_enh_fifo_pempty PORT_NAME_MAP ""
set_interface_property rx_enh_fifo_pempty CMSIS_SVD_VARIABLES ""
set_interface_property rx_enh_fifo_pempty SVD_ADDRESS_GROUP ""
set_interface_property rx_enh_fifo_pempty IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_enh_fifo_pempty rx_enh_fifo_pempty rx_enh_fifo_pempty Input 1


# 
# connection point tx_enh_fifo_pempty
# 
add_interface tx_enh_fifo_pempty conduit end
set_interface_property tx_enh_fifo_pempty associatedClock ""
set_interface_property tx_enh_fifo_pempty associatedReset ""
set_interface_property tx_enh_fifo_pempty ENABLED true
set_interface_property tx_enh_fifo_pempty EXPORT_OF ""
set_interface_property tx_enh_fifo_pempty PORT_NAME_MAP ""
set_interface_property tx_enh_fifo_pempty CMSIS_SVD_VARIABLES ""
set_interface_property tx_enh_fifo_pempty SVD_ADDRESS_GROUP ""
set_interface_property tx_enh_fifo_pempty IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_enh_fifo_pempty tx_enh_fifo_pempty tx_enh_fifo_pempty Input 1


# 
# connection point tx_enh_fifo_empty
# 
add_interface tx_enh_fifo_empty conduit end
set_interface_property tx_enh_fifo_empty associatedClock ""
set_interface_property tx_enh_fifo_empty associatedReset ""
set_interface_property tx_enh_fifo_empty ENABLED true
set_interface_property tx_enh_fifo_empty EXPORT_OF ""
set_interface_property tx_enh_fifo_empty PORT_NAME_MAP ""
set_interface_property tx_enh_fifo_empty CMSIS_SVD_VARIABLES ""
set_interface_property tx_enh_fifo_empty SVD_ADDRESS_GROUP ""
set_interface_property tx_enh_fifo_empty IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_enh_fifo_empty tx_enh_fifo_empty tx_enh_fifo_empty Input 1


# 
# connection point tx_enh_fifo_pfull
# 
add_interface tx_enh_fifo_pfull conduit end
set_interface_property tx_enh_fifo_pfull associatedClock ""
set_interface_property tx_enh_fifo_pfull associatedReset ""
set_interface_property tx_enh_fifo_pfull ENABLED true
set_interface_property tx_enh_fifo_pfull EXPORT_OF ""
set_interface_property tx_enh_fifo_pfull PORT_NAME_MAP ""
set_interface_property tx_enh_fifo_pfull CMSIS_SVD_VARIABLES ""
set_interface_property tx_enh_fifo_pfull SVD_ADDRESS_GROUP ""
set_interface_property tx_enh_fifo_pfull IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_enh_fifo_pfull tx_enh_fifo_pfull tx_enh_fifo_pfull Input 1


# 
# connection point tx_enh_fifo_full
# 
add_interface tx_enh_fifo_full conduit end
set_interface_property tx_enh_fifo_full associatedClock ""
set_interface_property tx_enh_fifo_full associatedReset ""
set_interface_property tx_enh_fifo_full ENABLED true
set_interface_property tx_enh_fifo_full EXPORT_OF ""
set_interface_property tx_enh_fifo_full PORT_NAME_MAP ""
set_interface_property tx_enh_fifo_full CMSIS_SVD_VARIABLES ""
set_interface_property tx_enh_fifo_full SVD_ADDRESS_GROUP ""
set_interface_property tx_enh_fifo_full IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_enh_fifo_full tx_enh_fifo_full tx_enh_fifo_full Input 1


# 
# connection point avm_m0
# 
add_interface avm_m0 avalon start
set_interface_property avm_m0 addressGroup 0
set_interface_property avm_m0 addressUnits SYMBOLS
set_interface_property avm_m0 associatedClock clk
set_interface_property avm_m0 associatedReset rst
set_interface_property avm_m0 bitsPerSymbol 8
set_interface_property avm_m0 burstOnBurstBoundariesOnly false
set_interface_property avm_m0 burstcountUnits WORDS
set_interface_property avm_m0 doStreamReads false
set_interface_property avm_m0 doStreamWrites false
set_interface_property avm_m0 holdTime 0
set_interface_property avm_m0 linewrapBursts false
set_interface_property avm_m0 maximumPendingReadTransactions 0
set_interface_property avm_m0 maximumPendingWriteTransactions 0
set_interface_property avm_m0 minimumResponseLatency 1
set_interface_property avm_m0 readLatency 0
set_interface_property avm_m0 readWaitTime 1
set_interface_property avm_m0 setupTime 0
set_interface_property avm_m0 timingUnits Cycles
set_interface_property avm_m0 waitrequestAllowance 0
set_interface_property avm_m0 writeWaitTime 0
set_interface_property avm_m0 ENABLED true
set_interface_property avm_m0 EXPORT_OF ""
set_interface_property avm_m0 PORT_NAME_MAP ""
set_interface_property avm_m0 CMSIS_SVD_VARIABLES ""
set_interface_property avm_m0 SVD_ADDRESS_GROUP ""
set_interface_property avm_m0 IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port avm_m0 avm_m0_address address Output 32
add_interface_port avm_m0 avm_m0_read read Output 1
add_interface_port avm_m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port avm_m0 avm_m0_readdata readdata Input 32
add_interface_port avm_m0 avm_m0_readdatavalid readdatavalid Input 1
add_interface_port avm_m0 avm_m0_write write Output 1
add_interface_port avm_m0 avm_m0_writedata writedata Output 32


# 
# connection point tx_control
# 
add_interface tx_control conduit end
set_interface_property tx_control associatedClock ""
set_interface_property tx_control associatedReset ""
set_interface_property tx_control ENABLED true
set_interface_property tx_control EXPORT_OF ""
set_interface_property tx_control PORT_NAME_MAP ""
set_interface_property tx_control CMSIS_SVD_VARIABLES ""
set_interface_property tx_control SVD_ADDRESS_GROUP ""
set_interface_property tx_control IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_control tx_control tx_control Output 3


# 
# connection point rx_control
# 
add_interface rx_control conduit end
set_interface_property rx_control associatedClock ""
set_interface_property rx_control associatedReset ""
set_interface_property rx_control ENABLED true
set_interface_property rx_control EXPORT_OF ""
set_interface_property rx_control PORT_NAME_MAP ""
set_interface_property rx_control CMSIS_SVD_VARIABLES ""
set_interface_property rx_control SVD_ADDRESS_GROUP ""
set_interface_property rx_control IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_control rx_control rx_control Input 10


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock ""
set_interface_property rst synchronousEdges NONE
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""
set_interface_property rst IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rst reset reset Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""
set_interface_property clk IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clk clock clk Input 1


# 
# connection point tx_ready
# 
add_interface tx_ready conduit end
set_interface_property tx_ready associatedClock ""
set_interface_property tx_ready associatedReset ""
set_interface_property tx_ready ENABLED true
set_interface_property tx_ready EXPORT_OF ""
set_interface_property tx_ready PORT_NAME_MAP ""
set_interface_property tx_ready CMSIS_SVD_VARIABLES ""
set_interface_property tx_ready SVD_ADDRESS_GROUP ""
set_interface_property tx_ready IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_ready tx_ready tx_ready Input 1


# 
# connection point rx_ready
# 
add_interface rx_ready conduit end
set_interface_property rx_ready associatedClock ""
set_interface_property rx_ready associatedReset ""
set_interface_property rx_ready ENABLED true
set_interface_property rx_ready EXPORT_OF ""
set_interface_property rx_ready PORT_NAME_MAP ""
set_interface_property rx_ready CMSIS_SVD_VARIABLES ""
set_interface_property rx_ready SVD_ADDRESS_GROUP ""
set_interface_property rx_ready IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_ready rx_ready rx_ready Input 1


# 
# connection point irq_rx
# 
add_interface irq_rx interrupt end
set_interface_property irq_rx associatedClock clk
set_interface_property irq_rx associatedReset rst
set_interface_property irq_rx bridgedReceiverOffset ""
set_interface_property irq_rx bridgesToReceiver ""
set_interface_property irq_rx ENABLED true
set_interface_property irq_rx EXPORT_OF ""
set_interface_property irq_rx PORT_NAME_MAP ""
set_interface_property irq_rx CMSIS_SVD_VARIABLES ""
set_interface_property irq_rx SVD_ADDRESS_GROUP ""
set_interface_property irq_rx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port irq_rx rx_irq irq Output 1


# 
# connection point tx_enh_data_valid
# 
add_interface tx_enh_data_valid conduit end
set_interface_property tx_enh_data_valid associatedClock ""
set_interface_property tx_enh_data_valid associatedReset ""
set_interface_property tx_enh_data_valid ENABLED true
set_interface_property tx_enh_data_valid EXPORT_OF ""
set_interface_property tx_enh_data_valid PORT_NAME_MAP ""
set_interface_property tx_enh_data_valid CMSIS_SVD_VARIABLES ""
set_interface_property tx_enh_data_valid SVD_ADDRESS_GROUP ""
set_interface_property tx_enh_data_valid IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_enh_data_valid tx_enh_data_valid tx_enh_data_valid Output 1


# 
# connection point irq_tx
# 
add_interface irq_tx interrupt end
set_interface_property irq_tx associatedClock clk
set_interface_property irq_tx associatedReset rst
set_interface_property irq_tx bridgedReceiverOffset ""
set_interface_property irq_tx bridgesToReceiver ""
set_interface_property irq_tx ENABLED true
set_interface_property irq_tx EXPORT_OF ""
set_interface_property irq_tx PORT_NAME_MAP ""
set_interface_property irq_tx CMSIS_SVD_VARIABLES ""
set_interface_property irq_tx SVD_ADDRESS_GROUP ""
set_interface_property irq_tx IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port irq_tx tx_irq irq Output 1


# 
# connection point tx_coreclkin
# 
add_interface tx_coreclkin clock end
set_interface_property tx_coreclkin ENABLED true
set_interface_property tx_coreclkin EXPORT_OF ""
set_interface_property tx_coreclkin PORT_NAME_MAP ""
set_interface_property tx_coreclkin CMSIS_SVD_VARIABLES ""
set_interface_property tx_coreclkin SVD_ADDRESS_GROUP ""
set_interface_property tx_coreclkin IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_coreclkin tx_coreclkin clk Input 1


# 
# connection point rx_coreclkin
# 
add_interface rx_coreclkin clock end
set_interface_property rx_coreclkin ENABLED true
set_interface_property rx_coreclkin EXPORT_OF ""
set_interface_property rx_coreclkin PORT_NAME_MAP ""
set_interface_property rx_coreclkin CMSIS_SVD_VARIABLES ""
set_interface_property rx_coreclkin SVD_ADDRESS_GROUP ""
set_interface_property rx_coreclkin IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_coreclkin rx_coreclkin clk Input 1


# 
# connection point rx_enh_fifo_rd_en
# 
add_interface rx_enh_fifo_rd_en conduit end
set_interface_property rx_enh_fifo_rd_en associatedClock ""
set_interface_property rx_enh_fifo_rd_en associatedReset ""
set_interface_property rx_enh_fifo_rd_en ENABLED true
set_interface_property rx_enh_fifo_rd_en EXPORT_OF ""
set_interface_property rx_enh_fifo_rd_en PORT_NAME_MAP ""
set_interface_property rx_enh_fifo_rd_en CMSIS_SVD_VARIABLES ""
set_interface_property rx_enh_fifo_rd_en SVD_ADDRESS_GROUP ""
set_interface_property rx_enh_fifo_rd_en IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_enh_fifo_rd_en rx_enh_fifo_rd_en rx_enh_fifo_rd_en Output 1


# 
# connection point tx_err_ins
# 
add_interface tx_err_ins conduit end
set_interface_property tx_err_ins associatedClock ""
set_interface_property tx_err_ins associatedReset ""
set_interface_property tx_err_ins ENABLED true
set_interface_property tx_err_ins EXPORT_OF ""
set_interface_property tx_err_ins PORT_NAME_MAP ""
set_interface_property tx_err_ins CMSIS_SVD_VARIABLES ""
set_interface_property tx_err_ins SVD_ADDRESS_GROUP ""
set_interface_property tx_err_ins IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_err_ins tx_err_ins tx_err_ins Output 1


# 
# connection point reset_phy
# 
add_interface reset_phy reset start
set_interface_property reset_phy associatedClock clk
set_interface_property reset_phy associatedDirectReset ""
set_interface_property reset_phy associatedResetSinks ""
set_interface_property reset_phy synchronousEdges DEASSERT
set_interface_property reset_phy ENABLED true
set_interface_property reset_phy EXPORT_OF ""
set_interface_property reset_phy PORT_NAME_MAP ""
set_interface_property reset_phy CMSIS_SVD_VARIABLES ""
set_interface_property reset_phy SVD_ADDRESS_GROUP ""
set_interface_property reset_phy IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port reset_phy reset_phy reset Output 1


# 
# connection point pll_locked_out
# 
add_interface pll_locked_out conduit end
set_interface_property pll_locked_out associatedClock ""
set_interface_property pll_locked_out associatedReset ""
set_interface_property pll_locked_out ENABLED true
set_interface_property pll_locked_out EXPORT_OF ""
set_interface_property pll_locked_out PORT_NAME_MAP ""
set_interface_property pll_locked_out CMSIS_SVD_VARIABLES ""
set_interface_property pll_locked_out SVD_ADDRESS_GROUP ""
set_interface_property pll_locked_out IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port pll_locked_out pll_locked_out pll_locked Output 1


# 
# connection point pll_powerdown_input
# 
add_interface pll_powerdown_input conduit end
set_interface_property pll_powerdown_input associatedClock ""
set_interface_property pll_powerdown_input associatedReset ""
set_interface_property pll_powerdown_input ENABLED true
set_interface_property pll_powerdown_input EXPORT_OF ""
set_interface_property pll_powerdown_input PORT_NAME_MAP ""
set_interface_property pll_powerdown_input CMSIS_SVD_VARIABLES ""
set_interface_property pll_powerdown_input SVD_ADDRESS_GROUP ""
set_interface_property pll_powerdown_input IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port pll_powerdown_input pll_powerdown_input pll_powerdown Input 1


# 
# connection point atx_pll_powerdown
# 
add_interface atx_pll_powerdown conduit end
set_interface_property atx_pll_powerdown associatedClock ""
set_interface_property atx_pll_powerdown associatedReset ""
set_interface_property atx_pll_powerdown ENABLED true
set_interface_property atx_pll_powerdown EXPORT_OF ""
set_interface_property atx_pll_powerdown PORT_NAME_MAP ""
set_interface_property atx_pll_powerdown CMSIS_SVD_VARIABLES ""
set_interface_property atx_pll_powerdown SVD_ADDRESS_GROUP ""
set_interface_property atx_pll_powerdown IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port atx_pll_powerdown atx_pll_powerdown pll_powerdown Output 1


# 
# connection point atx_pll_locked
# 
add_interface atx_pll_locked conduit end
set_interface_property atx_pll_locked associatedClock ""
set_interface_property atx_pll_locked associatedReset ""
set_interface_property atx_pll_locked ENABLED true
set_interface_property atx_pll_locked EXPORT_OF ""
set_interface_property atx_pll_locked PORT_NAME_MAP ""
set_interface_property atx_pll_locked CMSIS_SVD_VARIABLES ""
set_interface_property atx_pll_locked SVD_ADDRESS_GROUP ""
set_interface_property atx_pll_locked IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port atx_pll_locked atx_pll_locked pll_locked Input 1


# 
# connection point rx_set_locktodata
# 
add_interface rx_set_locktodata conduit end
set_interface_property rx_set_locktodata associatedClock ""
set_interface_property rx_set_locktodata associatedReset ""
set_interface_property rx_set_locktodata ENABLED true
set_interface_property rx_set_locktodata EXPORT_OF ""
set_interface_property rx_set_locktodata PORT_NAME_MAP ""
set_interface_property rx_set_locktodata CMSIS_SVD_VARIABLES ""
set_interface_property rx_set_locktodata SVD_ADDRESS_GROUP ""
set_interface_property rx_set_locktodata IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_set_locktodata rx_set_locktodata rx_set_locktodata Output 1


# 
# connection point rx_set_locktoref
# 
add_interface rx_set_locktoref conduit end
set_interface_property rx_set_locktoref associatedClock ""
set_interface_property rx_set_locktoref associatedReset ""
set_interface_property rx_set_locktoref ENABLED true
set_interface_property rx_set_locktoref EXPORT_OF ""
set_interface_property rx_set_locktoref PORT_NAME_MAP ""
set_interface_property rx_set_locktoref CMSIS_SVD_VARIABLES ""
set_interface_property rx_set_locktoref SVD_ADDRESS_GROUP ""
set_interface_property rx_set_locktoref IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_set_locktoref rx_set_locktoref rx_set_locktoref Output 1


# 
# connection point tx_enh_frame_burst_en
# 
add_interface tx_enh_frame_burst_en conduit end
set_interface_property tx_enh_frame_burst_en associatedClock ""
set_interface_property tx_enh_frame_burst_en associatedReset ""
set_interface_property tx_enh_frame_burst_en ENABLED true
set_interface_property tx_enh_frame_burst_en EXPORT_OF ""
set_interface_property tx_enh_frame_burst_en PORT_NAME_MAP ""
set_interface_property tx_enh_frame_burst_en CMSIS_SVD_VARIABLES ""
set_interface_property tx_enh_frame_burst_en SVD_ADDRESS_GROUP ""
set_interface_property tx_enh_frame_burst_en IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_enh_frame_burst_en tx_enh_frame_burst_en tx_enh_frame_burst_en Output 1


# 
# connection point tx_enh_frame_diag_status
# 
add_interface tx_enh_frame_diag_status conduit end
set_interface_property tx_enh_frame_diag_status associatedClock ""
set_interface_property tx_enh_frame_diag_status associatedReset ""
set_interface_property tx_enh_frame_diag_status ENABLED true
set_interface_property tx_enh_frame_diag_status EXPORT_OF ""
set_interface_property tx_enh_frame_diag_status PORT_NAME_MAP ""
set_interface_property tx_enh_frame_diag_status CMSIS_SVD_VARIABLES ""
set_interface_property tx_enh_frame_diag_status SVD_ADDRESS_GROUP ""
set_interface_property tx_enh_frame_diag_status IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port tx_enh_frame_diag_status tx_enh_frame_diag_status tx_enh_frame_diag_status Output 2


# 
# connection point unused_tx_control
# 
add_interface unused_tx_control conduit end
set_interface_property unused_tx_control associatedClock ""
set_interface_property unused_tx_control associatedReset ""
set_interface_property unused_tx_control ENABLED true
set_interface_property unused_tx_control EXPORT_OF ""
set_interface_property unused_tx_control PORT_NAME_MAP ""
set_interface_property unused_tx_control CMSIS_SVD_VARIABLES ""
set_interface_property unused_tx_control SVD_ADDRESS_GROUP ""
set_interface_property unused_tx_control IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port unused_tx_control unused_tx_control unused_tx_control Output 14


# 
# connection point unused_tx_parallel_data
# 
add_interface unused_tx_parallel_data conduit end
set_interface_property unused_tx_parallel_data associatedClock ""
set_interface_property unused_tx_parallel_data associatedReset ""
set_interface_property unused_tx_parallel_data ENABLED true
set_interface_property unused_tx_parallel_data EXPORT_OF ""
set_interface_property unused_tx_parallel_data PORT_NAME_MAP ""
set_interface_property unused_tx_parallel_data CMSIS_SVD_VARIABLES ""
set_interface_property unused_tx_parallel_data SVD_ADDRESS_GROUP ""
set_interface_property unused_tx_parallel_data IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port unused_tx_parallel_data unused_tx_parallel_data unused_tx_parallel_data Output 64


# 
# connection point rx_seriallpbken
# 
add_interface rx_seriallpbken conduit end
set_interface_property rx_seriallpbken associatedClock ""
set_interface_property rx_seriallpbken associatedReset ""
set_interface_property rx_seriallpbken ENABLED true
set_interface_property rx_seriallpbken EXPORT_OF ""
set_interface_property rx_seriallpbken PORT_NAME_MAP ""
set_interface_property rx_seriallpbken CMSIS_SVD_VARIABLES ""
set_interface_property rx_seriallpbken SVD_ADDRESS_GROUP ""
set_interface_property rx_seriallpbken IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_seriallpbken rx_seriallpbken rx_seriallpbken Output 1


# 
# connection point pll_select
# 
add_interface pll_select conduit end
set_interface_property pll_select associatedClock ""
set_interface_property pll_select associatedReset ""
set_interface_property pll_select ENABLED true
set_interface_property pll_select EXPORT_OF ""
set_interface_property pll_select PORT_NAME_MAP ""
set_interface_property pll_select CMSIS_SVD_VARIABLES ""
set_interface_property pll_select SVD_ADDRESS_GROUP ""
set_interface_property pll_select IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port pll_select pll_select pll_select Output 1


# 
# connection point rx_enh_frame_diag_status
# 
add_interface rx_enh_frame_diag_status conduit end
set_interface_property rx_enh_frame_diag_status associatedClock ""
set_interface_property rx_enh_frame_diag_status associatedReset ""
set_interface_property rx_enh_frame_diag_status ENABLED true
set_interface_property rx_enh_frame_diag_status EXPORT_OF ""
set_interface_property rx_enh_frame_diag_status PORT_NAME_MAP ""
set_interface_property rx_enh_frame_diag_status CMSIS_SVD_VARIABLES ""
set_interface_property rx_enh_frame_diag_status SVD_ADDRESS_GROUP ""
set_interface_property rx_enh_frame_diag_status IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rx_enh_frame_diag_status rx_enh_frame_diag_status rx_enh_frame_diag_status Input 2

