config system_bd_altera_emif_181_i6g4tza_cfg;
		design system_bd_altera_emif_181_i6g4tza;
		instance system_bd_altera_emif_181_i6g4tza.arch use system_bd_altera_emif_arch_nf_181.system_bd_altera_emif_arch_nf_181_yepuh6a;
		instance system_bd_altera_emif_181_i6g4tza.cal_slave_component use system_bd_altera_emif_cal_slave_nf_181.system_bd_altera_emif_cal_slave_nf_181_fflgvsa;
endconfig

