config system_bd_altera_eth_tse_181_3w7teoy_cfg;
		design system_bd_altera_eth_tse_181_3w7teoy;
		instance system_bd_altera_eth_tse_181_3w7teoy.i_tse_mac use system_bd_altera_eth_tse_mac_181.altera_eth_tse_mac;
		instance system_bd_altera_eth_tse_181_3w7teoy.avalon_arbiter use system_bd_altera_eth_tse_avalon_arbiter_181.altera_eth_tse_avalon_arbiter;
		instance system_bd_altera_eth_tse_181_3w7teoy.i_tse_pcs_0 use system_bd_altera_eth_tse_pcs_pma_nf_lvds_181.altera_eth_tse_pcs_pma_nf_lvds;
		instance system_bd_altera_eth_tse_181_3w7teoy.i_lvdsio_rx_0 use system_bd_altera_lvds_181.system_bd_altera_lvds_181_ha24u6i;
		instance system_bd_altera_eth_tse_181_3w7teoy.i_lvdsio_tx_0 use system_bd_altera_lvds_181.system_bd_altera_lvds_181_mkcsf5q;
		instance system_bd_altera_eth_tse_181_3w7teoy.i_lvdsio_terminator_0 use system_bd_altera_eth_tse_nf_lvds_terminator_181.altera_eth_tse_nf_lvds_terminator;
		instance system_bd_altera_eth_tse_181_3w7teoy.rst_controller use system_bd_altera_reset_controller_181.altera_reset_controller;
		instance system_bd_altera_eth_tse_181_3w7teoy.rst_controller_001 use system_bd_altera_reset_controller_181.altera_reset_controller;
		instance system_bd_altera_eth_tse_181_3w7teoy.rst_controller_002 use system_bd_altera_reset_controller_181.altera_reset_controller;
endconfig

