// mcu_subsystem_pio_0.v

// Generated using ACDS version 18.1.2 277

`timescale 1 ps / 1 ps
module mcu_subsystem_pio_0 (
		input  wire        clk,        //                 clk.clk
		input  wire        reset_n,    //               reset.reset_n
		input  wire [2:0]  address,    //                  s1.address
		input  wire        write_n,    //                    .write_n
		input  wire [31:0] writedata,  //                    .writedata
		input  wire        chipselect, //                    .chipselect
		output wire [31:0] readdata,   //                    .readdata
		input  wire [31:0] in_port,    // external_connection.in_port
		output wire [31:0] out_port,   //                    .out_port
		output wire        irq         //                 irq.irq
	);

	mcu_subsystem_pio_0_altera_avalon_pio_181_7tsabby pio_0 (
		.clk        (clk),        //   input,   width = 1,                 clk.clk
		.reset_n    (reset_n),    //   input,   width = 1,               reset.reset_n
		.address    (address),    //   input,   width = 3,                  s1.address
		.write_n    (write_n),    //   input,   width = 1,                    .write_n
		.writedata  (writedata),  //   input,  width = 32,                    .writedata
		.chipselect (chipselect), //   input,   width = 1,                    .chipselect
		.readdata   (readdata),   //  output,  width = 32,                    .readdata
		.in_port    (in_port),    //   input,  width = 32, external_connection.export
		.out_port   (out_port),   //  output,  width = 32,                    .export
		.irq        (irq)         //  output,   width = 1,                 irq.irq
	);

endmodule
