config system_bd_altera_lvds_181_mkcsf5q_cfg;
		design system_bd_altera_lvds_181_mkcsf5q;
		instance system_bd_altera_lvds_181_mkcsf5q.core use system_bd_altera_lvds_core20_181.system_bd_altera_lvds_core20_181_y5hozjy;
endconfig

