config system_bd_altera_mm_interconnect_181_boiywzi_cfg;
		design system_bd_altera_mm_interconnect_181_boiywzi;
		instance system_bd_altera_mm_interconnect_181_boiywzi.sys_cpu_tightly_coupled_data_master_0_translator use system_bd_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance system_bd_altera_mm_interconnect_181_boiywzi.sys_tlb_mem_s1_translator use system_bd_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
endconfig

