config system_bd_altera_avalon_st_adapter_181_pkulkta_cfg;
		design system_bd_altera_avalon_st_adapter_181_pkulkta;
		instance system_bd_altera_avalon_st_adapter_181_pkulkta.timing_adapter_0 use system_bd_timing_adapter_181.system_bd_timing_adapter_181_4ceyadi;
endconfig

