config system_bd_altera_arria10_hps_io_181_sktkmzq_cfg;
		design system_bd_altera_arria10_hps_io_181_sktkmzq;
		instance system_bd_altera_arria10_hps_io_181_sktkmzq.border use system_bd_altera_arria10_interface_generator_140.system_bd_altera_arria10_interface_generator_140_as2bmya;
endconfig

