config system_bd_altera_mm_interconnect_181_uehknzy_cfg;
		design system_bd_altera_mm_interconnect_181_uehknzy;
		instance system_bd_altera_mm_interconnect_181_uehknzy.sys_cpu_tightly_coupled_instruction_master_0_translator use system_bd_altera_merlin_master_translator_181.altera_merlin_master_translator;
		instance system_bd_altera_mm_interconnect_181_uehknzy.sys_tlb_mem_s2_translator use system_bd_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
endconfig

