// mcu_subsystem_generic_quad_spi_controller2_0_altera_generic_quad_spi_controller2_181_5xz3lbq.v

// This file was auto-generated from generic_qspi_controller2_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1.2 277

`timescale 1 ps / 1 ps
module mcu_subsystem_generic_quad_spi_controller2_0_altera_generic_quad_spi_controller2_181_5xz3lbq #(
		parameter DEVICE_FAMILY     = "Cyclone 10 GX",
		parameter CS_WIDTH          = 3,
		parameter ADDR_WIDTH        = 25,
		parameter ASI_WIDTH         = 4,
		parameter ASMI_ADDR_WIDTH   = 32,
		parameter ENABLE_4BYTE_ADDR = 1,
		parameter IO_MODE           = "QUAD",
		parameter CHIP_SELS         = 1
	) (
		input  wire                  clk,                  //       clock_sink.clk
		input  wire                  reset_n,              //            reset.reset_n
		output wire                  qspi_pins_dclk,       //        qspi_pins.dclk
		output wire                  qspi_pins_ncs,        //                 .ncs
		inout  wire [3:0]            qspi_pins_data,       //                 .data
		input  wire                  avl_csr_read,         //          avl_csr.read
		output wire                  avl_csr_waitrequest,  //                 .waitrequest
		input  wire                  avl_csr_write,        //                 .write
		input  wire [3:0]            avl_csr_addr,         //                 .address
		input  wire [31:0]           avl_csr_wrdata,       //                 .writedata
		output wire [31:0]           avl_csr_rddata,       //                 .readdata
		output wire                  avl_csr_rddata_valid, //                 .readdatavalid
		input  wire                  avl_mem_write,        //          avl_mem.write
		input  wire [6:0]            avl_mem_burstcount,   //                 .burstcount
		output wire                  avl_mem_waitrequest,  //                 .waitrequest
		input  wire                  avl_mem_read,         //                 .read
		input  wire [ADDR_WIDTH-1:0] avl_mem_addr,         //                 .address
		input  wire [31:0]           avl_mem_wrdata,       //                 .writedata
		output wire [31:0]           avl_mem_rddata,       //                 .readdata
		output wire                  avl_mem_rddata_valid, //                 .readdatavalid
		input  wire [3:0]            avl_mem_byteenable,   //                 .byteenable
		output wire                  irq                   // interrupt_sender.irq
	);

	wire  [31:0] addr_adaption_1_asmi_mem_readdata;       // asmi2_inst_qspi_ctrl:avl_mem_readdata -> addr_adaption_1:asmi_mem_rddata
	wire         addr_adaption_1_asmi_mem_waitrequest;    // asmi2_inst_qspi_ctrl:avl_mem_waitrequest -> addr_adaption_1:asmi_mem_waitrequest
	wire  [31:0] addr_adaption_1_asmi_mem_address;        // addr_adaption_1:asmi_mem_addr -> asmi2_inst_qspi_ctrl:avl_mem_address
	wire         addr_adaption_1_asmi_mem_read;           // addr_adaption_1:asmi_mem_read -> asmi2_inst_qspi_ctrl:avl_mem_read
	wire   [3:0] addr_adaption_1_asmi_mem_byteenable;     // addr_adaption_1:asmi_mem_byteenable -> asmi2_inst_qspi_ctrl:avl_mem_byteenable
	wire         addr_adaption_1_asmi_mem_readdatavalid;  // asmi2_inst_qspi_ctrl:avl_mem_readdatavalid -> addr_adaption_1:asmi_mem_rddata_valid
	wire         addr_adaption_1_asmi_mem_write;          // addr_adaption_1:asmi_mem_write -> asmi2_inst_qspi_ctrl:avl_mem_write
	wire  [31:0] addr_adaption_1_asmi_mem_writedata;      // addr_adaption_1:asmi_mem_wrdata -> asmi2_inst_qspi_ctrl:avl_mem_writedata
	wire   [6:0] addr_adaption_1_asmi_mem_burstcount;     // addr_adaption_1:asmi_mem_burstcount -> asmi2_inst_qspi_ctrl:avl_mem_burstcount
	wire  [31:0] addr_adaption_1_asmi_csr_readdata;       // asmi2_inst_qspi_ctrl:avl_csr_readdata -> addr_adaption_1:asmi_csr_rddata
	wire         addr_adaption_1_asmi_csr_waitrequest;    // asmi2_inst_qspi_ctrl:avl_csr_waitrequest -> addr_adaption_1:asmi_csr_waitrequest
	wire   [5:0] addr_adaption_1_asmi_csr_address;        // addr_adaption_1:asmi_csr_addr -> asmi2_inst_qspi_ctrl:avl_csr_address
	wire         addr_adaption_1_asmi_csr_read;           // addr_adaption_1:asmi_csr_read -> asmi2_inst_qspi_ctrl:avl_csr_read
	wire         addr_adaption_1_asmi_csr_readdatavalid;  // asmi2_inst_qspi_ctrl:avl_csr_readdatavalid -> addr_adaption_1:asmi_csr_rddata_valid
	wire         addr_adaption_1_asmi_csr_write;          // addr_adaption_1:asmi_csr_write -> asmi2_inst_qspi_ctrl:avl_csr_write
	wire  [31:0] addr_adaption_1_asmi_csr_writedata;      // addr_adaption_1:asmi_csr_wrdata -> asmi2_inst_qspi_ctrl:avl_csr_writedata
	wire   [3:0] addr_adaption_1_chip_select_chip_select; // addr_adaption_1:chip_select -> asmi2_inst_qspi_ctrl:chip_select_chip_select

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (DEVICE_FAMILY != "Cyclone 10 GX")
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					device_family_check ( .error(1'b1) );
		end
		if (CS_WIDTH != 3)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					cs_width_check ( .error(1'b1) );
		end
		if (ADDR_WIDTH != 25)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					addr_width_check ( .error(1'b1) );
		end
		if (ASI_WIDTH != 4)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					asi_width_check ( .error(1'b1) );
		end
		if (ASMI_ADDR_WIDTH != 32)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					asmi_addr_width_check ( .error(1'b1) );
		end
		if (ENABLE_4BYTE_ADDR != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					enable_4byte_addr_check ( .error(1'b1) );
		end
		if (IO_MODE != "QUAD")
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					io_mode_check ( .error(1'b1) );
		end
		if (CHIP_SELS != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					chip_sels_check ( .error(1'b1) );
		end
	endgenerate

	mcu_subsystem_generic_quad_spi_controller2_0_altera_asmi_parallel2_181_jbbczgq #(
		.WR_ID_LIST      ("0 1 2"),
		.RD_ID_LIST      ("0 1 2 3"),
		.DEVICE_FAMILY   ("Cyclone 10 GX"),
		.ASMI_ADDR_WIDTH (32),
		.CHIP_SELS       (1)
	) asmi2_inst_qspi_ctrl (
		.avl_csr_address         (addr_adaption_1_asmi_csr_address),        //   input,   width = 6,     avl_csr.address
		.avl_csr_read            (addr_adaption_1_asmi_csr_read),           //   input,   width = 1,            .read
		.avl_csr_readdata        (addr_adaption_1_asmi_csr_readdata),       //  output,  width = 32,            .readdata
		.avl_csr_write           (addr_adaption_1_asmi_csr_write),          //   input,   width = 1,            .write
		.avl_csr_writedata       (addr_adaption_1_asmi_csr_writedata),      //   input,  width = 32,            .writedata
		.avl_csr_waitrequest     (addr_adaption_1_asmi_csr_waitrequest),    //  output,   width = 1,            .waitrequest
		.avl_csr_readdatavalid   (addr_adaption_1_asmi_csr_readdatavalid),  //  output,   width = 1,            .readdatavalid
		.avl_mem_address         (addr_adaption_1_asmi_mem_address),        //   input,  width = 32,     avl_mem.address
		.avl_mem_read            (addr_adaption_1_asmi_mem_read),           //   input,   width = 1,            .read
		.avl_mem_readdata        (addr_adaption_1_asmi_mem_readdata),       //  output,  width = 32,            .readdata
		.avl_mem_write           (addr_adaption_1_asmi_mem_write),          //   input,   width = 1,            .write
		.avl_mem_writedata       (addr_adaption_1_asmi_mem_writedata),      //   input,  width = 32,            .writedata
		.avl_mem_byteenable      (addr_adaption_1_asmi_mem_byteenable),     //   input,   width = 4,            .byteenable
		.avl_mem_burstcount      (addr_adaption_1_asmi_mem_burstcount),     //   input,   width = 7,            .burstcount
		.avl_mem_waitrequest     (addr_adaption_1_asmi_mem_waitrequest),    //  output,   width = 1,            .waitrequest
		.avl_mem_readdatavalid   (addr_adaption_1_asmi_mem_readdatavalid),  //  output,   width = 1,            .readdatavalid
		.chip_select_chip_select (addr_adaption_1_chip_select_chip_select), //   input,   width = 4, chip_select.chip_select
		.clk_clk                 (clk),                                     //   input,   width = 1,         clk.clk
		.reset_reset             (~reset_n),                                //   input,   width = 1,       reset.reset
		.qspi_pins_dclk          (qspi_pins_dclk),                          //  output,   width = 1,   qspi_pins.dclk
		.qspi_pins_ncs           (qspi_pins_ncs),                           //  output,   width = 1,            .ncs
		.qspi_pins_data          (qspi_pins_data)                           //   inout,   width = 4,            .data
	);

	altera_qspi_address_adaption #(
		.DEVICE_FAMILY     ("Cyclone 10 GX"),
		.ADDR_WIDTH        (25),
		.ASMI_ADDR_WIDTH   (32),
		.ASI_WIDTH         (4),
		.CS_WIDTH          (3),
		.CHIP_SELS         (1),
		.ENABLE_4BYTE_ADDR (1)
	) addr_adaption_1 (
		.clk                   (clk),                                     //   input,   width = 1,       clock_sink.clk
		.reset                 (~reset_n),                                //   input,   width = 1,            reset.reset
		.avl_csr_read          (avl_csr_read),                            //   input,   width = 1,          avl_csr.read
		.avl_csr_waitrequest   (avl_csr_waitrequest),                     //  output,   width = 1,                 .waitrequest
		.avl_csr_write         (avl_csr_write),                           //   input,   width = 1,                 .write
		.avl_csr_addr          (avl_csr_addr),                            //   input,   width = 4,                 .address
		.avl_csr_wrdata        (avl_csr_wrdata),                          //   input,  width = 32,                 .writedata
		.avl_csr_rddata        (avl_csr_rddata),                          //  output,  width = 32,                 .readdata
		.avl_csr_rddata_valid  (avl_csr_rddata_valid),                    //  output,   width = 1,                 .readdatavalid
		.asmi_csr_addr         (addr_adaption_1_asmi_csr_address),        //  output,   width = 6,         asmi_csr.address
		.asmi_csr_read         (addr_adaption_1_asmi_csr_read),           //  output,   width = 1,                 .read
		.asmi_csr_rddata       (addr_adaption_1_asmi_csr_readdata),       //   input,  width = 32,                 .readdata
		.asmi_csr_write        (addr_adaption_1_asmi_csr_write),          //  output,   width = 1,                 .write
		.asmi_csr_wrdata       (addr_adaption_1_asmi_csr_writedata),      //  output,  width = 32,                 .writedata
		.asmi_csr_waitrequest  (addr_adaption_1_asmi_csr_waitrequest),    //   input,   width = 1,                 .waitrequest
		.asmi_csr_rddata_valid (addr_adaption_1_asmi_csr_readdatavalid),  //   input,   width = 1,                 .readdatavalid
		.avl_mem_write         (avl_mem_write),                           //   input,   width = 1,          avl_mem.write
		.avl_mem_burstcount    (avl_mem_burstcount),                      //   input,   width = 7,                 .burstcount
		.avl_mem_waitrequest   (avl_mem_waitrequest),                     //  output,   width = 1,                 .waitrequest
		.avl_mem_read          (avl_mem_read),                            //   input,   width = 1,                 .read
		.avl_mem_addr          (avl_mem_addr),                            //   input,  width = 25,                 .address
		.avl_mem_wrdata        (avl_mem_wrdata),                          //   input,  width = 32,                 .writedata
		.avl_mem_rddata        (avl_mem_rddata),                          //  output,  width = 32,                 .readdata
		.avl_mem_rddata_valid  (avl_mem_rddata_valid),                    //  output,   width = 1,                 .readdatavalid
		.avl_mem_byteenable    (avl_mem_byteenable),                      //   input,   width = 4,                 .byteenable
		.asmi_mem_addr         (addr_adaption_1_asmi_mem_address),        //  output,  width = 32,         asmi_mem.address
		.asmi_mem_read         (addr_adaption_1_asmi_mem_read),           //  output,   width = 1,                 .read
		.asmi_mem_rddata       (addr_adaption_1_asmi_mem_readdata),       //   input,  width = 32,                 .readdata
		.asmi_mem_write        (addr_adaption_1_asmi_mem_write),          //  output,   width = 1,                 .write
		.asmi_mem_wrdata       (addr_adaption_1_asmi_mem_writedata),      //  output,  width = 32,                 .writedata
		.asmi_mem_byteenable   (addr_adaption_1_asmi_mem_byteenable),     //  output,   width = 4,                 .byteenable
		.asmi_mem_burstcount   (addr_adaption_1_asmi_mem_burstcount),     //  output,   width = 7,                 .burstcount
		.asmi_mem_waitrequest  (addr_adaption_1_asmi_mem_waitrequest),    //   input,   width = 1,                 .waitrequest
		.asmi_mem_rddata_valid (addr_adaption_1_asmi_mem_readdatavalid),  //   input,   width = 1,                 .readdatavalid
		.irq                   (irq),                                     //  output,   width = 1, interrupt_sender.irq
		.chip_select           (addr_adaption_1_chip_select_chip_select)  //  output,   width = 4,      chip_select.chip_select
	);

endmodule
