config system_bd_altera_generic_tristate_controller_181_o6vsvpq_cfg;
		design system_bd_altera_generic_tristate_controller_181_o6vsvpq;
		instance system_bd_altera_generic_tristate_controller_181_o6vsvpq.tdt use system_bd_altera_tristate_controller_translator_181.altera_tristate_controller_translator;
		instance system_bd_altera_generic_tristate_controller_181_o6vsvpq.slave_translator use system_bd_altera_merlin_slave_translator_181.altera_merlin_slave_translator;
		instance system_bd_altera_generic_tristate_controller_181_o6vsvpq.tda use system_bd_altera_tristate_controller_aggregator_181.altera_tristate_controller_aggregator;
endconfig

