// ethernet_iopll.v

// Generated using ACDS version 18.1.2 277

`timescale 1 ps / 1 ps
module ethernet_iopll (
		input  wire  rst,      //   reset.reset
		input  wire  refclk,   //  refclk.clk
		output wire  outclk_0  // outclk0.clk
	);

	ethernet_iopll_altera_iopll_181_7d7bofq ethernet_iopll (
		.rst      (rst),      //   input,  width = 1,   reset.reset
		.refclk   (refclk),   //   input,  width = 1,  refclk.clk
		.outclk_0 (outclk_0)  //  output,  width = 1, outclk0.clk
	);

endmodule
