config system_bd_alt_mem_asym_10_wryanuq_cfg;
		design system_bd_alt_mem_asym_10_wryanuq;
		instance system_bd_alt_mem_asym_10_wryanuq.alt_mem use system_bd_ram_2port_181.system_bd_ram_2port_181_sebxbea;
endconfig

