config system_bd_altera_emif_cal_slave_nf_181_c5oooyy_cfg;
		design system_bd_altera_emif_cal_slave_nf_181_c5oooyy;
		instance system_bd_altera_emif_cal_slave_nf_181_c5oooyy.ioaux_master_bridge use system_bd_altera_avalon_mm_bridge_181.altera_avalon_mm_bridge;
		instance system_bd_altera_emif_cal_slave_nf_181_c5oooyy.ioaux_soft_ram use system_bd_altera_avalon_onchip_memory2_181.system_bd_altera_avalon_onchip_memory2_181_76knrqa;
		instance system_bd_altera_emif_cal_slave_nf_181_c5oooyy.mm_interconnect_0 use system_bd_altera_mm_interconnect_181.system_bd_altera_mm_interconnect_181_cazrnua;
		instance system_bd_altera_emif_cal_slave_nf_181_c5oooyy.rst_controller use system_bd_altera_reset_controller_181.altera_reset_controller;
endconfig

